/**
 * The manager's side of the Docker Postgres instance it owns
 * (documentation/docker_postgres.md). The container, volume and network
 * handling and the daemon check are core (`@goobster/core/db/docker`); this
 * file composes them with the manager's settings, the instance record
 * (`<store>/docker-postgres.json`) and the #338 connection library, which
 * does the role, extension and schema work against `127.0.0.1:<port>` like
 * for any other server.
 *
 * Secrets: the superuser and the application password are generated by the
 * caller (passwords.js) and passed in; they reach the container through the
 * child environment and the library through a connection object, never an
 * argv, a record, a plan, a journal or a result. The application URL is
 * staged in the overlay under a key that is never merged into an environment
 * (environment.js STAGED_KEYS) until `database.connect` writes the live one.
 */

const nodeFs = require('node:fs');
const nodePath = require('node:path');
const { ManagerError } = require('../errors');
const environment = require('../environment');
const dbInit = require('../install/dbInit');
const { exactKeys, parseBoolean } = require('../install/engine');
const { lazy } = require('../lazy');
const { createProbe } = require('../database/probe');
const input = require('../database/input');
const state = require('./state');
const passwords = require('./passwords');

const lib = lazy('@goobster/core/db/docker');

const REQUEST_KEYS = new Set(['port', 'bind', 'acknowledgeLanBind', 'storage', 'role', 'database', 'memoryMb', 'pull', 'acknowledgeBackupTools']);
const NAME = /^[a-z_][a-z0-9_]{0,62}$/;
const IPV4 = /^(?:\d{1,3}\.){3}\d{1,3}$/;
const ACTIONS = Object.freeze(['create-role', 'create-database', 'create-extension.citext', 'create-extension.vector', 'create-schema', 'grant']);
const REQUIRED_BYTES = 1024 * 1024 * 1024;
const STAGED = 'GOOBSTER_DOCKER_DB_URL';

const finding = (code, severity, detail, remedy = '', extra = {}) => ({ code, severity, detail, remedy, ...extra });

function invalid(message) {
    return new ManagerError(400, 'INVALID_INPUT', message);
}

/** A core `DockerError` as the manager's error; anything else is returned unchanged. */
function mapDocker(error) {
    if (!error || error.name !== 'DockerError') return error;
    const status = error.code === 'INVALID_PORT' || error.code === 'INVALID_PASSWORD' || error.code === 'INVALID_INSTALLATION_ID' ? 400 : 409;
    return new ManagerError(status, error.code, error.message, error.details && Object.keys(error.details).length ? error.details : null);
}

async function mapped(call) {
    try {
        return await call();
    } catch (error) {
        throw mapDocker(error);
    }
}

function parseStorage(value) {
    if (value === undefined || value === null) return { kind: 'volume' };
    exactKeys(value, new Set(['kind', 'path']), '"docker.storage"');
    if (value.kind === 'volume') {
        if (value.path !== undefined) throw invalid('"docker.storage.path" only applies to storage kind "path".');
        return { kind: 'volume' };
    }
    if (value.kind !== 'path') throw invalid('"docker.storage.kind" must be "volume" or "path".');
    const text = value.path;
    if (typeof text !== 'string' || text.length === 0 || text.length > 1024 || text.includes('\0') || !nodePath.isAbsolute(text) || text.split(/[\\/]/).includes('..')) {
        throw invalid('"docker.storage.path" must be an absolute directory path without ".." segments.');
    }
    if (text.includes(':') && process.platform !== 'win32') throw invalid('"docker.storage.path" cannot contain ":" (Docker reads it as a mount separator).');
    return { kind: 'path', path: nodePath.normalize(text) };
}

/**
 * The operator's request, validated. A bind address other than loopback is an
 * explicit choice (`acknowledgeLanBind`); the default never leaves this host.
 */
function parseRequest(raw, { keys = REQUEST_KEYS } = {}) {
    const value = raw === undefined || raw === null ? {} : raw;
    exactKeys(value, keys, '"docker"');
    const port = value.port === undefined ? 5432 : value.port;
    if (!Number.isInteger(port) || port < 1 || port > 65535) throw invalid('"docker.port" must be a whole number from 1 to 65535.');
    const bind = value.bind === undefined ? '127.0.0.1' : value.bind;
    if (typeof bind !== 'string' || !IPV4.test(bind) || bind.split('.').some(part => Number(part) > 255)) throw invalid('"docker.bind" must be an IPv4 address (default 127.0.0.1).');
    const lan = bind !== '127.0.0.1';
    const acknowledgeLanBind = parseBoolean(value.acknowledgeLanBind, 'docker.acknowledgeLanBind', false);
    if (lan && !acknowledgeLanBind) {
        throw new ManagerError(400, 'LAN_BIND_NOT_ACKNOWLEDGED', `Binding the database to ${bind === '0.0.0.0' ? 'every network interface' : bind} makes it reachable from other machines. Leave "docker.bind" at 127.0.0.1, or set "docker.acknowledgeLanBind" to accept that.`);
    }
    const role = value.role === undefined ? 'goobster' : value.role;
    const database = value.database === undefined ? 'goobster' : value.database;
    if (typeof role !== 'string' || !NAME.test(role) || role === 'postgres') throw invalid('"docker.role" must be a lowercase role name (letters, digits, "_") other than "postgres".');
    if (typeof database !== 'string' || !NAME.test(database) || database === 'postgres' || database.startsWith('template')) throw invalid('"docker.database" must be a lowercase database name other than "postgres" or a template.');
    let memoryMb = null;
    if (value.memoryMb !== undefined && value.memoryMb !== null) {
        if (!Number.isInteger(value.memoryMb) || value.memoryMb < 256 || value.memoryMb > 1048576) throw invalid('"docker.memoryMb" must be a whole number of megabytes from 256 to 1048576.');
        memoryMb = value.memoryMb;
    }
    return {
        port,
        bind,
        lan,
        acknowledgeLanBind,
        storage: parseStorage(value.storage),
        role,
        database,
        memoryMb,
        pull: parseBoolean(value.pull, 'docker.pull', false),
        acknowledgeBackupTools: parseBoolean(value.acknowledgeBackupTools, 'docker.acknowledgeBackupTools', false)
    };
}

/** The request as a plan or a response may show it: no secret exists in it, and names only for the account. */
function publicRequest(request) {
    return {
        port: request.port,
        bind: request.bind,
        storage: request.storage.kind === 'path' ? { kind: 'path', path: request.storage.path } : { kind: 'volume' },
        role: request.role,
        database: request.database,
        memoryMb: request.memoryMb,
        lan: request.lan
    };
}

function createDockerService({ settings, fs = nodeFs, now = () => new Date(), logger = console }) {
    const deps = () => settings.dockerDeps || {};
    const databaseDeps = () => settings.databaseDeps || {};

    function processEnv() {
        const base = { ...process.env };
        const own = settings.processEnv || {};
        for (const key of ['DOCKER_HOST', 'GOOBSTER_DOCKER_BIN', 'GOOBSTER_PG_BIN', 'PATH', 'DOCKER_CONFIG', 'DOCKER_CONTEXT', 'HOME']) {
            if (own[key] !== undefined) base[key] = own[key];
        }
        return base;
    }

    const runner = () => deps().docker || lib.createRunner({ env: processEnv() });
    const containersFor = (installationId) => lib.createContainers({
        docker: runner(),
        installationId,
        deps: { ...(deps().sleep ? { sleep: deps().sleep } : {}), ...(deps().probeListen ? { probeListen: deps().probeListen } : {}) }
    });
    const record = () => state.read(settings.storeDir, fs);
    const resourceNames = (installationId) => {
        if (!installationId) return { container: 'goobster-pg-<id8>', volume: 'goobster-pgdata-<id8>', network: 'goobster-<id8>', template: true };
        const resources = lib.resourcesFor(installationId);
        return { container: resources.container.name, volume: resources.volume.name, network: resources.network.name, template: false };
    };

    // ------------------------------------------------------------- the daemon
    async function check({ storagePath = null, requiredBytes = null } = {}) {
        return lib.checkDaemon({
            docker: runner(),
            env: processEnv(),
            fs,
            ...(deps().pgDump ? { pgDump: deps().pgDump } : {}),
            ...(deps().platform ? { platform: deps().platform } : {}),
            ...(deps().hostArch ? { hostArch: deps().hostArch } : {}),
            storagePath,
            requiredBytes
        });
    }

    function storageFindings(request, daemon) {
        const out = [];
        if (request.storage.kind !== 'path') return { findings: out, path: null };
        const target = request.storage.path;
        let stat = null;
        try { stat = fs.statSync(target); } catch { /* may be created */ }
        if (stat && !stat.isDirectory()) {
            out.push(finding('STORAGE_NOT_DIRECTORY', 'block', 'The chosen storage path exists and is not a directory.', 'Choose a directory, or a path that does not exist yet.'));
            return { findings: out, path: target };
        }
        if (stat) {
            let entries = [];
            try { entries = fs.readdirSync(target); } catch { out.push(finding('STORAGE_UNREADABLE', 'block', 'The chosen storage directory cannot be read by the manager.', 'Fix its permissions, or choose another path.')); }
            if (entries.includes('pgdata')) {
                out.push(finding('STORAGE_HAS_DATA', 'block', 'The chosen directory already holds a "pgdata" database directory.', 'Provisioning creates a new database and never adopts one, because its superuser password is unknown to this installer. Choose an empty directory, or move that one away yourself.'));
            }
            // The image's postgres account (not the manager's) works inside the mount: it has to be
            // able to enter the directory, or initdb fails and the container never becomes healthy.
            if (process.platform !== 'win32' && (stat.mode & 0o011) === 0) {
                out.push(finding('STORAGE_NOT_ENTERABLE', 'block', 'Only its owner may enter the chosen directory; the database account inside the container cannot.', `Allow search access (chmod o+x '${target}'), or choose another directory. The database directory the container creates inside it stays private to that account.`));
            }
        } else {
            const parent = lib.nearestExisting(fs, target);
            let writable = false;
            try { if (parent) { fs.accessSync(parent, nodeFs.constants.W_OK); writable = true; } } catch { /* not writable */ }
            if (!writable) out.push(finding('STORAGE_NOT_CREATABLE', 'block', 'The chosen storage path does not exist and its parent cannot be written by the manager.', 'Create the directory yourself, or choose a path the manager user may write.'));
        }
        if (daemon.daemon.flavor === 'desktop') {
            out.push(finding('STORAGE_DESKTOP_SHARING', 'note', 'On Docker Desktop a host directory is shared into the virtual machine.', 'It must be in Docker Desktop\'s file-sharing list; performance and permissions differ from a Docker volume.'));
        }
        return { findings: out, path: target };
    }

    // ----------------------------------------------------- inspecting what exists
    /** What this installation's three resources look like right now. Throws nothing for a foreign resource: it is reported. */
    async function inspectResources(installationId) {
        const containers = containersFor(installationId);
        const out = { container: null, volume: false, network: false, foreign: [] };
        const probe = async (key, call) => {
            try {
                return await call();
            } catch (error) {
                if (error && error.code === 'RESOURCE_FOREIGN') {
                    out.foreign.push({ kind: error.details ? error.details.kind : key, name: error.details ? error.details.name : null });
                    return null;
                }
                throw error;
            }
        };
        const names = containers.resources;
        out.container = await probe('container', async () => containers.summarizeContainer(await containers.inspectOwned(names.container)));
        out.volume = Boolean(await probe('volume', () => containers.inspectOwned(names.volume)));
        out.network = Boolean(await probe('network', () => containers.inspectOwned(names.network)));
        return out;
    }

    function publicRecord(doc) {
        if (!doc) return null;
        return {
            step: doc.step,
            complete: doc.step === 'verified',
            image: doc.image,
            request: { port: doc.request.port, bind: doc.request.bind, storage: doc.request.storage, role: doc.request.role, database: doc.request.database, memoryMb: doc.request.memoryMb },
            created: doc.created,
            dataInitialised: doc.dataInitialised,
            updatedAt: doc.updatedAt
        };
    }

    /** True when the connection in effect is the instance this manager owns (loopback, the recorded port). */
    function connectedToOwned(doc) {
        if (!doc || doc.step !== 'verified' || !settings.dbUrl) return false;
        try {
            const target = input.connectionLib.describeUrl(settings.dbUrl);
            return input.connectionLib.isLoopback(target.host) && Number(target.port) === doc.request.port;
        } catch {
            return false;
        }
    }

    /** The read-only view for `GET /docker/status` and `database docker status`. */
    async function status({ installationId = null, storagePath = null } = {}) {
        const daemon = await check({ storagePath });
        const read = record();
        const view = {
            daemon,
            names: resourceNames(installationId),
            record: publicRecord(read.doc),
            recordProblem: read.problem,
            owned: null,
            connected: connectedToOwned(read.doc)
        };
        if (installationId && daemon.daemon.reachable && read.present) {
            const found = await mapped(() => inspectResources(installationId));
            view.owned = { container: found.container, volume: found.volume, network: found.network, foreign: found.foreign };
        }
        return view;
    }

    // ----------------------------------------------------------------- planning
    /**
     * Everything provisioning needs to know before it changes anything: the
     * daemon, what already exists (and whether this is a resume), the port, the
     * storage and the image. `blocks` stop the operation; each carries a remedy.
     * `installationId` is null while planning a fresh install (the id exists
     * only after the ownership step), so nothing of ours can exist yet.
     */
    async function assess({ installationId, request }) {
        const daemon = await check({ storagePath: request.storage.kind === 'path' ? request.storage.path : null, requiredBytes: REQUIRED_BYTES });
        const findings = [...daemon.verdict.blocks.map(item => ({ ...item, severity: 'block' })), ...daemon.verdict.warnings.map(item => ({ ...item, severity: 'warn' })), ...daemon.verdict.notes.map(item => ({ ...item, severity: 'note' }))];
        const view = {
            daemon,
            names: resourceNames(installationId),
            request: publicRequest(request),
            mode: 'fresh',
            existing: null,
            port: { requested: request.port, chosen: request.port, free: null, reason: null, suggestion: null },
            storage: { kind: request.storage.kind, path: request.storage.kind === 'path' ? request.storage.path : null },
            image: { reference: daemon.image.humanReference, digest: daemon.image.digest, postgresMajor: daemon.image.postgresMajor, pulled: daemon.image.pulled, pullBytes: daemon.image.pullBytes, willPull: false },
            backupTools: daemon.backupTools,
            findings,
            ok: false
        };
        if (request.lan) findings.push(finding('LAN_BIND', 'warn', `The database will listen on ${request.bind}, which other machines may reach.`, 'Put a firewall in front of it, or bind 127.0.0.1.'));
        const backup = daemon.backupTools;
        if (backup && !backup.ok) {
            const index = findings.findIndex(item => item.code === backup.code);
            const entry = finding(backup.code, request.acknowledgeBackupTools ? 'warn' : 'block', backup.code === 'BACKUP_TOOLS_MISSING' ? 'pg_dump is not installed here, so Goobster\'s backups cannot read this database.' : `The host's pg_dump (${backup.version || 'unknown'}) is older than the server's PostgreSQL ${daemon.image.postgresMajor}; it refuses to back it up.`, backup.remedy, { blocksBackups: true, acknowledge: 'acknowledgeBackupTools' });
            if (index >= 0) findings[index] = entry; else findings.push(entry);
        }
        if (daemon.verdict.blocks.length > 0) return finish(view);

        const { findings: storage } = storageFindings(request, daemon);
        findings.push(...storage);

        const earlier = record();
        if (earlier.doc && String(earlier.doc.installationId).toLowerCase() !== (installationId ? String(installationId).toLowerCase() : null)) {
            findings.push(finding('RECORD_OF_ANOTHER_INSTALLATION', 'block', 'The manager store records a Docker database that belongs to another installation (it was kept when that installation was uninstalled).', 'Its container and data volume are still there. Remove them by uninstalling with removeDockerData next time, or by name with docker rm / docker volume rm (the names are in docker-postgres.json\'s installation id), then try again.'));
        } else if (installationId) {
            const read = earlier;
            if (read.present && !read.doc) findings.push(finding('RECORD_UNREADABLE', 'block', 'docker-postgres.json in the manager store cannot be read.', 'It was left as it is; inspect it, or move it away if the instance is gone.'));
            const found = await mapped(() => inspectResources(installationId));
            view.existing = { record: publicRecord(read.doc), container: found.container, volume: found.volume, network: found.network, foreign: found.foreign };
            for (const item of found.foreign) findings.push(finding('RESOURCE_FOREIGN', 'block', `A ${item.kind} named "${item.name}" exists without this installation's labels. It is not touched.`, 'Rename or remove it yourself, or choose another installation.', { resource: item }));
            const doc = read.doc;
            const any = Boolean(found.container && found.container.exists) || found.volume || found.network;
            if (doc && doc.step === 'verified') {
                findings.push(finding('ALREADY_PROVISIONED', 'block', 'This installation already has a Docker database.', 'Use "database docker start", "stop" or "repair". To start over, remove it first (uninstall with removeDockerData).'));
            } else if (doc && rankOf(doc.step) >= rankOf('container')) {
                view.mode = 'recreate';
                if (doc.request.storage.kind === 'path' && fs.existsSync(nodePath.join(doc.request.storage.path, 'pgdata'))) {
                    findings.push(finding('STORAGE_INITIALISED', 'block', 'An earlier setup stopped after the database initialised the chosen directory, and the password it was started with was never saved.', 'Empty the "pgdata" folder inside it yourself (the installer never deletes a folder you chose), or choose another path. Then provision again.'));
                } else if (doc.request.storage.kind === 'path') {
                    findings.push(finding('RESUME_RECREATE', 'note', 'An earlier setup stopped while the container was being created. The chosen directory holds no database yet, so the installer removes this installation\'s own container (by name, after checking its labels) and creates it again.', ''));
                } else {
                    findings.push(finding('RESUME_RECREATE', 'note', 'An earlier setup stopped after the container started. Its data volume holds a database whose password was never saved, so the installer removes this installation\'s own container and volume (by name, after checking their labels) and creates them again.', ''));
                }
            } else if (doc) {
                view.mode = 'resume';
                findings.push(finding('RESUME', 'note', `An earlier setup reached "${doc.step}"; it continues from there with this installation's own resources.`, ''));
            } else if (any && found.foreign.length === 0) {
                findings.push(finding('RESOURCES_WITHOUT_RECORD', 'block', 'Resources carrying this installation\'s labels exist but the manager has no record of creating them.', 'They may hold data. Inspect them (docker ps -a --filter label=io.goobster.installation=...), remove them yourself if they are leftovers, then provision again.'));
            }
        }

        const containers = installationId ? containersFor(installationId) : containersFor('00000000-0000-4000-8000-000000000000');
        const ownPort = view.existing && view.existing.container && view.existing.container.exists ? view.existing.container.port : null;
        if (ownPort !== request.port) {
            const status = await mapped(() => containers.portStatus(request.port, request.bind === '0.0.0.0' ? '127.0.0.1' : request.bind));
            view.port.free = status.free;
            view.port.reason = status.reason;
            if (!status.free) {
                const next = await mapped(() => containers.nextFreePort(request.port + 1, request.bind));
                view.port.suggestion = next;
                findings.push(finding('PORT_IN_USE', 'block', status.reason === 'CONTAINER_PUBLISHES' ? `Port ${request.port} is published by another container (${status.container}).` : `Something on this machine already listens on port ${request.port}.`, next ? `Choose another port; ${next} is free.` : 'Choose another port.', { port: request.port, suggestion: next }));
            }
        } else {
            view.port.free = true;
        }

        if (!daemon.image.pulled) {
            view.image.willPull = request.pull;
            if (!request.pull) findings.push(finding('IMAGE_PULL_NOT_APPROVED', 'block', `The database image (${daemon.image.humanReference}) is not on this machine and pulling it downloads about ${Math.round((daemon.image.pullBytes || 160e6) / 1e6)} MB.`, 'Tick "pull the image" to approve the download.', { pullBytes: daemon.image.pullBytes, acknowledge: 'pull' }));
        }
        return finish(view);
    }

    const rankOf = (step) => state.rank(step);

    function finish(view) {
        view.ok = !view.findings.some(item => item.severity === 'block');
        view.blocks = view.findings.filter(item => item.severity === 'block').map(item => ({ code: item.code, detail: item.detail, remedy: item.remedy }));
        return view;
    }

    function assertAssessed(view) {
        if (view.ok) return;
        const codes = [...new Set(view.blocks.map(item => item.code))];
        throw new ManagerError(409, 'PREFLIGHT_FAILED', `The Docker database cannot be created yet: ${codes.join(', ')}.`, { findings: view.blocks.slice(0, 12) });
    }

    // -------------------------------------------------------------- the creation
    function startRecord(installationId, request, operationId) {
        const pinned = lib.pinned();
        return state.write(settings.storeDir, {
            installationId,
            image: { reference: pinned.humanReference, major: pinned.postgresMajor, minor: pinned.postgresMinor },
            request: { port: request.port, bind: request.bind, storage: request.storage, role: request.role, database: request.database, memoryMb: request.memoryMb },
            step: 'planned',
            created: { network: false, volume: false, container: false },
            dataInitialised: false,
            operationId
        }, { fs, now });
    }

    const advance = (step, patch = {}) => state.update(settings.storeDir, { step, ...patch }, { fs, now });

    /** Remove what an earlier, interrupted setup of THIS installation created (names re-checked against labels). */
    async function cleanInterrupted(installationId, doc) {
        const containers = containersFor(installationId);
        const removed = [];
        if ((await mapped(() => containers.removeContainer())).removed) removed.push('container');
        if (doc.request.storage.kind === 'volume' && (await mapped(() => containers.removeVolume())).removed) removed.push('volume');
        removeStaged();
        return removed;
    }

    /** network, volume or directory, then the container. Returns what was created. */
    async function createResources({ installationId, request, superuserPassword, operationId, view }) {
        const containers = containersFor(installationId);
        const read = record();
        let doc = read.doc;
        const done = { network: false, volume: false, container: false, cleaned: [] };
        if (doc && rankOf(doc.step) >= rankOf('container')) {
            done.cleaned = await cleanInterrupted(installationId, doc);
            doc = null;
        }
        if (!doc) doc = startRecord(installationId, request, operationId);
        else doc = state.update(settings.storeDir, { operationId, request: { port: request.port, bind: request.bind, storage: request.storage, role: request.role, database: request.database, memoryMb: request.memoryMb } }, { fs, now });

        done.network = (await mapped(() => containers.ensureNetwork())).created;
        advance('network', { created: { network: doc.created.network || done.network } });
        if (request.storage.kind === 'volume') {
            done.volume = (await mapped(() => containers.ensureVolume())).created;
        } else {
            // Enterable by the container's postgres account; the pgdata directory it creates inside is 0700 and its own.
            fs.mkdirSync(request.storage.path, { recursive: true, mode: 0o755 });
            done.volume = true;
        }
        advance('volume', { created: { volume: doc.created.volume || done.volume } });
        if (view && !view.image.pulled) {
            if (!request.pull) throw new ManagerError(409, 'IMAGE_PULL_NOT_APPROVED', 'The database image is not on this machine and pulling it was not approved.');
            await mapped(() => containers.pull());
        }
        advance('container', { dataInitialised: false });
        await mapped(() => containers.createContainer({ port: request.port, bind: request.bind, storage: request.storage, memoryMb: request.memoryMb, superuserPassword }));
        done.container = true;
        advance('container', { created: { container: true }, dataInitialised: true });
        return done;
    }

    async function waitHealthy({ installationId }) {
        const containers = containersFor(installationId);
        const out = await mapped(() => containers.waitHealthy({ ...(deps().waitMs ? { timeoutMs: deps().waitMs } : {}), ...(deps().pollMs ? { pollMs: deps().pollMs } : {}) }));
        advance('healthy');
        return { health: out.health, status: out.status };
    }

    /** The application's connection to the instance: the loopback published port, no TLS (the image has none), the generated password. */
    function applicationConnection(request, password) {
        return input.parseConnection({
            host: '127.0.0.1',
            port: request.port,
            database: request.database,
            schema: 'public',
            user: request.role,
            password,
            tls: { mode: 'disable' }
        });
    }

    function stageUrl(url) {
        const existing = environment.read(settings.storeDir, fs).values;
        environment.write(settings.storeDir, { ...existing, [STAGED]: url }, { fs, now });
    }

    function removeStaged() {
        const existing = environment.read(settings.storeDir, fs);
        if (!existing.values[STAGED]) return false;
        const { [STAGED]: _gone, ...rest } = existing.values;
        if (Object.keys(rest).length === 0) environment.remove(settings.storeDir, fs);
        else environment.write(settings.storeDir, rest, { fs, now });
        return true;
    }

    /** Role, database, extensions and grants through the #338 library, with the superuser the container was started with. */
    async function provisionRole({ request, passwords: secret }) {
        const application = applicationConnection(request, secret.application);
        stageUrl(input.connectionLib.connectionUrl(application, { tlsMode: 'disable' }));
        const run = databaseDeps().runProvisioning || input.connectionLib.runProvisioning;
        const out = await input.mapped(() => run({
            application,
            elevated: { user: 'postgres', password: secret.superuser, database: 'postgres' },
            actions: ACTIONS,
            tlsMode: 'disable',
            ...(databaseDeps().provisioningDeps || {})
        }));
        advance('provisioned');
        return { application, results: out.results };
    }

    async function applySchema({ roots, request, url }) {
        const initialise = databaseDeps().initDatabase || dbInit.initDatabase;
        const out = await initialise({ roots: roots || { data: settings.dataDir, code: settings.root }, settings, database: { engine: 'postgres', external: true }, url });
        advance('schema');
        return { tables: out.tables };
    }

    async function verify({ application }) {
        const report = await createProbe(settings)(application);
        const found = report.schema ? report.schema.state : 'missing-schema';
        if (!report.reachable || found !== 'goobster-current') {
            throw new ManagerError(409, 'SCHEMA_NOT_CURRENT', `The new database's schema is ${found}; nothing else was changed.`);
        }
        advance('verified');
        return { schema: found, ok: report.verdict.ok };
    }

    function urlOf(application) {
        return input.connectionLib.connectionUrl(application, { tlsMode: 'disable' });
    }

    // ------------------------------------------------------------- lifecycle
    function recorded() {
        const read = record();
        if (!read.doc) throw new ManagerError(409, 'NO_DOCKER_DATABASE', 'This manager has no Docker database record. Provision one first (database docker provision).');
        return read.doc;
    }

    async function start({ installationId }) {
        const doc = recorded();
        const containers = containersFor(installationId);
        const summary = await mapped(() => containers.container());
        if (!summary.exists) throw new ManagerError(409, 'CONTAINER_MISSING', 'The database container does not exist. Repair it (database docker repair): the data volume is kept.');
        if (!summary.running) await mapped(() => containers.start());
        const waited = await mapped(() => containers.waitHealthy({ ...(deps().waitMs ? { timeoutMs: deps().waitMs } : {}), ...(deps().pollMs ? { pollMs: deps().pollMs } : {}) }));
        return { running: true, health: waited.health, port: doc.request.port };
    }

    async function stop({ installationId }) {
        recorded();
        const containers = containersFor(installationId);
        const out = await mapped(() => containers.stop());
        return { stopped: out.stopped, missing: out.missing };
    }

    /** A container over existing data ignores POSTGRES_PASSWORD; the CLI wrapper still requires one, so it gets a value nobody keeps. */
    const throwaway = () => passwords.generate();

    /** What a repair would do: nothing, recreate the container over the same storage, or refuse. */
    async function repairPlan({ installationId }) {
        const doc = recorded();
        const found = await mapped(() => inspectResources(installationId));
        const findings = [];
        for (const item of found.foreign) findings.push(finding('RESOURCE_FOREIGN', 'block', `A ${item.kind} named "${item.name}" exists without this installation's labels. It is not touched.`, 'Rename or remove it yourself.', { resource: item }));
        const summary = found.container || { exists: false };
        let action = 'none';
        const reasons = [];
        if (!summary.exists) {
            action = 'recreate';
            reasons.push('MISSING');
        } else {
            if (!summary.imagePinned) reasons.push('IMAGE_DRIFT');
            if (summary.restartPolicy !== 'unless-stopped') reasons.push('RESTART_POLICY');
            if (summary.hasHealthCheck === false) reasons.push('NO_HEALTH_CHECK');
            if (summary.port !== doc.request.port || summary.bind !== doc.request.bind) reasons.push('PORT_DRIFT');
            if (reasons.length > 0) action = 'recreate';
            else if (!summary.running) action = 'start';
        }
        if (action === 'recreate') {
            const dataThere = doc.request.storage.kind === 'volume' ? found.volume : fs.existsSync(nodePath.join(doc.request.storage.path, 'pgdata'));
            if (!dataThere) findings.push(finding('DATA_MISSING', 'block', 'The data volume or directory is gone, so a new container would start an empty database.', 'Restore from a backup (documentation/backup_and_restore.md), or remove this record by uninstalling with removeDockerData and provision again.'));
        }
        const major = lib.planMajorChange({ currentMajor: doc.image.major });
        if (!major.ok) findings.push(finding(major.code, 'block', major.message, `See ${lib.UPGRADING_DOC}.`, { from: major.from, to: major.to }));
        const daemon = await check({});
        for (const item of daemon.verdict.blocks) findings.push({ ...item, severity: 'block' });
        return { action, reasons, container: summary, volume: found.volume, network: found.network, request: record().doc.request, findings, ok: !findings.some(item => item.severity === 'block'), blocks: findings.filter(item => item.severity === 'block').map(item => ({ code: item.code, detail: item.detail, remedy: item.remedy })) };
    }

    async function repair({ installationId }) {
        const doc = recorded();
        const plan = await repairPlan({ installationId });
        if (!plan.ok) throw new ManagerError(409, 'PREFLIGHT_FAILED', `The Docker database cannot be repaired yet: ${[...new Set(plan.blocks.map(item => item.code))].join(', ')}.`, { findings: plan.blocks });
        const containers = containersFor(installationId);
        const done = { action: plan.action, recreated: false, started: false };
        if (plan.action === 'recreate') {
            await mapped(() => containers.removeContainer());
            await mapped(() => containers.ensureNetwork());
            const request = { ...doc.request };
            await mapped(() => containers.createContainer({ port: request.port, bind: request.bind, storage: request.storage, memoryMb: request.memoryMb, superuserPassword: throwaway() }));
            done.recreated = true;
        } else if (plan.action === 'start') {
            await mapped(() => containers.start());
            done.started = true;
        }
        return done;
    }

    /** Recreate over the same storage with a changed port, bind address or memory limit. */
    async function recreate({ installationId, changes }) {
        const doc = recorded();
        const containers = containersFor(installationId);
        const request = { ...doc.request, ...changes };
        await mapped(() => containers.removeContainer());
        await mapped(() => containers.ensureNetwork());
        await mapped(() => containers.createContainer({ port: request.port, bind: request.bind, storage: request.storage, memoryMb: request.memoryMb, superuserPassword: throwaway() }));
        state.update(settings.storeDir, { request: { port: request.port, bind: request.bind, memoryMb: request.memoryMb } }, { fs, now });
        return request;
    }

    /** The resources an uninstall with `removeDockerData` would delete, by name, and whether they exist. */
    async function removalPlan({ installationId }) {
        const read = record();
        if (!read.present) return { present: false, resources: [], foreign: [], record: null };
        const names = resourceNames(installationId);
        const doc = read.doc;
        const found = await mapped(() => inspectResources(installationId));
        const resources = [];
        if (found.container && found.container.exists) resources.push({ kind: 'container', name: names.container });
        if (found.volume && (!doc || doc.request.storage.kind === 'volume')) resources.push({ kind: 'volume', name: names.volume });
        if (found.network) resources.push({ kind: 'network', name: names.network });
        const path = doc && doc.request.storage.kind === 'path' ? doc.request.storage.path : null;
        return { present: true, record: publicRecord(doc), resources, foreign: found.foreign, hostPath: path };
    }

    /** Stop (keep) or remove (explicit scope). A host path the operator chose is never deleted by this code. */
    async function retire({ installationId, remove }) {
        const read = record();
        if (!read.present) return { present: false };
        const containers = containersFor(installationId);
        const out = { present: true, stopped: false, removed: [], keptHostPath: null };
        if (!remove) {
            out.stopped = (await mapped(() => containers.stop())).stopped;
            return out;
        }
        if ((await mapped(() => containers.removeContainer())).removed) out.removed.push('container');
        if ((await mapped(() => containers.removeVolume())).removed) out.removed.push('volume');
        if ((await mapped(() => containers.removeNetwork())).removed) out.removed.push('network');
        if (read.doc && read.doc.request.storage.kind === 'path') out.keptHostPath = read.doc.request.storage.path;
        removeStaged();
        state.remove(settings.storeDir, fs);
        return out;
    }

    return {
        parseRequest, publicRequest, check, status, assess, assertAssessed, startRecord, createResources, waitHealthy, provisionRole,
        applySchema, verify, applicationConnection, urlOf, stageUrl, removeStaged, start, stop, repairPlan, repair, recreate,
        removalPlan, retire, record, connectedToOwned, resourceNames, containersFor, inspectResources, publicRecord, advance,
        logger, now
    };
}

module.exports = { createDockerService, parseRequest, publicRequest, ACTIONS, STAGED, REQUEST_KEYS, REQUIRED_BYTES, mapDocker };
