/**
 * The portal side of the manager bridge (installer P2.1, issue #323).
 *
 * The browser never holds a manager credential. A portal route that has
 * already passed `requireAuth` + `requireOperator` asks this module for a
 * short-lived, single-purpose assertion bound to one manager request, and
 * calls the manager with it server-side:
 *
 *   payload  { v, purpose: 'manager', principalId, role, installationId,
 *              req: '<METHOD> <path>', iat, exp, nonce }   (exp - iat <= 300 s)
 *   token    'gma1.' + base64url(JSON payload) + '.' + base64url(HMAC-SHA256)
 *
 * The HMAC key and the installation id come from the manager's
 * `bridge-key` file (owner-only, generated by the manager), found at
 * GOOBSTER_MANAGER_BRIDGE_KEY_FILE or `<dataDir>/manager/bridge-key`.
 * The manager verifies signature, purpose, installation, expiry, request
 * binding and role, and refuses a nonce it has seen. Spec:
 * documentation/manager.md (Authenticated bridge).
 *
 * This module must not import anything under apps/.
 */

const nodeFs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');

const ASSERTION_PREFIX = 'gma1';
const ASSERTION_HEADER = 'x-goobster-manager-assertion';
const PURPOSE = 'manager';
const MAX_TTL_SECONDS = 300;
const DEFAULT_TTL_SECONDS = 60;
const BRIDGE_KEY_VERSION = 1;

class ManagerBridgeError extends Error {
    constructor(status, code, message) {
        super(message);
        this.name = 'ManagerBridgeError';
        this.status = status;
        this.code = code;
    }
}

function defaultKeyFile(env = process.env) {
    if (env.GOOBSTER_MANAGER_BRIDGE_KEY_FILE) return env.GOOBSTER_MANAGER_BRIDGE_KEY_FILE;
    if (env.GOOBSTER_MANAGER_STATE_DIR) return path.join(env.GOOBSTER_MANAGER_STATE_DIR, 'bridge-key');
    return path.join(env.GOOBSTER_DATA_DIR || require('../runtimePaths').dataDir, 'manager', 'bridge-key');
}

/** The `<prefix>.<payload>` text the HMAC covers. */
function signingInput(encodedPayload) {
    return `${ASSERTION_PREFIX}.${encodedPayload}`;
}

function sign(key, encodedPayload) {
    return crypto.createHmac('sha256', key).update(signingInput(encodedPayload)).digest('base64url');
}

/** Normalised request binding: upper-case method, path without query string. */
function requestBinding(method, requestPath) {
    const cleanPath = String(requestPath || '').split('?')[0];
    return `${String(method || '').toUpperCase()} ${cleanPath}`;
}

/**
 * Read the manager's bridge key file.
 * @returns {{ installationId: string, keyId: string, key: Buffer }}
 * @throws {ManagerBridgeError} 503 MANAGER_BRIDGE_UNAVAILABLE when missing or malformed (never echoes contents)
 */
function readBridgeKey(keyFile, fs = nodeFs) {
    let parsed;
    try {
        parsed = JSON.parse(fs.readFileSync(keyFile, 'utf8'));
    } catch {
        throw new ManagerBridgeError(503, 'MANAGER_BRIDGE_UNAVAILABLE', 'The manager bridge key is not available.');
    }
    if (!parsed || parsed.version !== BRIDGE_KEY_VERSION || typeof parsed.key !== 'string'
        || typeof parsed.installationId !== 'string' || typeof parsed.keyId !== 'string') {
        throw new ManagerBridgeError(503, 'MANAGER_BRIDGE_UNAVAILABLE', 'The manager bridge key is not available.');
    }
    const key = Buffer.from(parsed.key, 'base64url');
    if (key.length < 32) {
        throw new ManagerBridgeError(503, 'MANAGER_BRIDGE_UNAVAILABLE', 'The manager bridge key is not available.');
    }
    return { installationId: parsed.installationId, keyId: parsed.keyId, key };
}

/**
 * Mint one assertion. Pure: the caller supplies the key material.
 * @param {Object} params
 * @param {{ actorId: string, account: { role: string, status: string } | null }} params.actor from requireAuth
 * @param {{ installationId: string, key: Buffer }} params.bridgeKey
 * @param {string} params.method
 * @param {string} params.path manager path, e.g. /manager/api/operations
 * @param {number} [params.ttlSeconds] default 60, at most 300
 * @param {() => Date} [params.now]
 * @returns {string}
 */
function mintAssertion({ actor, bridgeKey, method, path: requestPath, ttlSeconds = DEFAULT_TTL_SECONDS, now = () => new Date() }) {
    if (!actor || !actor.actorId || actor.account?.role !== 'operator' || actor.account.status !== 'active') {
        throw new ManagerBridgeError(403, 'FORBIDDEN', 'Only the host can do that.');
    }
    if (!method || !requestPath || !String(requestPath).startsWith('/manager/api/')) {
        throw new ManagerBridgeError(400, 'BAD_REQUEST', 'A manager assertion is bound to one manager API request.');
    }
    const ttl = Math.max(1, Math.min(MAX_TTL_SECONDS, Math.floor(Number(ttlSeconds) || DEFAULT_TTL_SECONDS)));
    const iat = Math.floor(now().getTime() / 1000);
    const payload = {
        v: 1,
        purpose: PURPOSE,
        principalId: String(actor.actorId),
        role: 'operator',
        installationId: bridgeKey.installationId,
        req: requestBinding(method, requestPath),
        iat,
        exp: iat + ttl,
        nonce: crypto.randomBytes(16).toString('base64url')
    };
    const encoded = Buffer.from(JSON.stringify(payload), 'utf8').toString('base64url');
    return `${signingInput(encoded)}.${sign(bridgeKey.key, encoded)}`;
}

/**
 * The portal's handle: reads the key file on every mint (the manager may
 * rotate it on adoption) and returns the header to send.
 * @param {Object} [options]
 * @param {string} [options.keyFile]
 * @param {Object} [options.fs]
 * @param {() => Date} [options.now]
 */
function createManagerBridge(options = {}) {
    const keyFile = options.keyFile || defaultKeyFile(options.env || process.env);
    const fs = options.fs || nodeFs;
    const now = options.now || (() => new Date());
    return {
        keyFile,
        available() {
            try {
                readBridgeKey(keyFile, fs);
                return true;
            } catch {
                return false;
            }
        },
        mint({ actor, method, path: requestPath, ttlSeconds }) {
            return mintAssertion({ actor, bridgeKey: readBridgeKey(keyFile, fs), method, path: requestPath, ttlSeconds, now });
        },
        headers({ actor, method, path: requestPath, ttlSeconds }) {
            return { [ASSERTION_HEADER]: this.mint({ actor, method, path: requestPath, ttlSeconds }) };
        }
    };
}

module.exports = {
    ASSERTION_PREFIX,
    ASSERTION_HEADER,
    PURPOSE,
    MAX_TTL_SECONDS,
    DEFAULT_TTL_SECONDS,
    BRIDGE_KEY_VERSION,
    ManagerBridgeError,
    defaultKeyFile,
    signingInput,
    requestBinding,
    readBridgeKey,
    mintAssertion,
    createManagerBridge
};
