/** Prepared account/host demonstrations. Buttons change browser preview state only. */
const step = (id, title, body, path, before, action, after) => ({
    id, title, body, path, demo: 'workflow', preview: { before, action, after }
});
module.exports = [
    { id: 'settings.basics', roomId: 'settings', version: 2, title: 'Settings basics', steps: [
        step('display', 'Check the scope before saving', 'Settings labels distinguish this device, your account and private chats. Project and server controls have their own scopes.', '/settings/appearance', 'Sample display: comfortable spacing.', 'Preview compact spacing', 'Sample display: compact spacing. Your device and account preferences are unchanged.'),
        step('model-voice', 'Inspect model and voice choices', 'Chat and Voice list the choices available on this host. A preference cannot enable an unavailable provider.', '/settings/chat', 'Sample choice: use the host default.', 'Preview model and voice choices', 'Compare the available model in Chat and voice in Voice. No model request or audio playback occurs here.'),
        step('memory-retention', 'Separate memory controls from retention', 'Learning new memories, using existing memories and retaining chat history are separate decisions. Retention has its own preview and confirmation.', '/settings/memory', 'Sample: learning on, recall on, history retained.', 'Preview privacy choices', 'Turning learning off would stop future learning; it would not erase existing memories. Review retention separately. Nothing changed.'),
        step('quiet', 'Preview quiet hours', 'Initiative holds quiet hours and delivery preferences. Attention enrollment is a separate opt-in decision.', '/settings/initiative', 'Sample quiet hours: not set.', 'Preview quiet hours', 'Draft: 22:00–08:00 in the selected timezone. No hours, delivery destination or Attention enrollment changed.'),
        step('connections-devices', 'Inspect connections and sessions', 'Connections controls linked developer accounts. Account manages sign-in sessions. Revoking a session differs from disconnecting an integration.', '/settings/account', 'Sample: one linked integration and two sessions.', 'Inspect sample access', 'Choose the specific connection or session to revoke in its own control. This preview revokes nothing and exposes no credentials.'),
        step('tutorials', 'Find replay and reset', 'Settings → Tutorials lets you resume, replay or reset tours. Reset changes tutorial progress; it does not delete examples you explicitly kept.', '/settings/tutorials', 'Sample tutorial: paused.', 'Preview replay and reset', 'Resume continues progress. Replay starts a finished tour again. Reset clears its progress; kept notes remain.')
    ] },
    { id: 'memory.basics', roomId: 'settings', version: 2, title: 'Memory basics', steps: [
        step('copies', 'Distinguish the stored copies', 'A transcript records a conversation; a personal fact summarizes something about you; a saved note is knowledge you chose to keep.', '/settings/memory', 'Fictional transcript: “I study birds on Sundays.”', 'Compare sample copies', 'Fact: studies birds on Sundays. Saved note: a field observation. These are separate records; deleting one does not automatically delete the others.'),
        step('origin', 'Inspect why a memory exists', 'Inspect the type, scope and available provenance before trusting a remembered detail. Missing provenance is not evidence of correctness.', '/settings/memory', 'Sample remembered detail: studies birds on Sundays.', 'Inspect sample origin', 'Origin: a fictional private conversation. It is a personal detail, not a shared research note or a verified permanent preference.'),
        step('correction', 'Preview correction and deletion', 'Use the control for the record you intend to change. Forgetting a fact removes its mirrored fact node; deleting a raw memory also removes its recall vector.', '/settings/memory', 'Sample fact: studies birds on Sundays; now outdated.', 'Preview forgetting the fact', 'The sample fact and mirrored fact node would be removed. Source memories and transcripts would remain; correct or remove those separately as needed. No real record changed.'),
        step('future', 'Control future learning and recall', 'Learn memories controls future learning. Use memories controls recall. Neither toggle erases existing records.', '/settings/memory', 'Sample: learning enabled, recall enabled.', 'Preview learning off', 'Sample: learning off, recall still on. Existing memories could still be used. Your actual learning and recall choices are unchanged.'),
        step('retention', 'Review retention before applying it', 'Memory and chat-history retention are separate controls. Read the deletion preview before confirming a live change.', '/settings/memory', 'Sample history retention: keep forever.', 'Preview shorter retention', 'Sample preview: older chat transcripts would be removed. Saved notes and memories have separate lifetimes. No deletion or retention change occurs here.'),
        step('export-erasure', 'Inspect export and erasure scope', 'Export and Forget me are separate explicit flows. Inspect their scope before proceeding; downloaded copies and host-managed backups need separate handling.', '/settings/memory', 'Sample account: chats, memories, notes and shared copies.', 'Preview export and erasure', 'Export does not delete anything. Forget me has a broader scope than deleting one memory. Review the live confirmation, shared-copy details and host backup policy. This tour creates no export and erases nothing.')
    ] },
    { id: 'usage.basics', roomId: 'usage', version: 2, title: 'Usage basics', steps: [
        step('period', 'Choose the reporting period', 'Usage offers 7, 30 and 90 day views. The chart period is separate from the token-budget window.', '/usage', 'Sample chart: last 7 days, 1,200 tokens.', 'Preview 30 days', 'Sample chart: last 30 days, 4,800 tokens. Changing the reporting period does not change a budget or reset usage.'),
        step('breakdown', 'Inspect model and operation usage', 'Compare calls and token counts by model and operation. Provider token counts are not dollar prices.', '/usage', 'Sample total: 4,800 tokens.', 'Inspect sample breakdown', 'Sample operations: chat 3,000 tokens; summary 1,800 tokens. No dollar estimate is implied, and no provider is called.'),
        step('reserved', 'Distinguish reservations, alerts and caps', 'In-flight work reserves an estimate, then settles to actual usage. A usage alert is informational; a host token cap controls admission.', '/usage', 'Sample budget: 6,000 settled + 2,000 reserved of 10,000 tokens.', 'Inspect sample headroom', '2,000 tokens remain available in this sample window. Reserved tokens are not all final usage. A chart or alert alone is not the budget ledger.'),
        step('waiting', 'Understand waiting and quota failures', 'Waiting for execution capacity differs from waiting for token budget. Inspect the reason and the displayed reset time before retrying.', '/usage', 'Sample request needs 3,000 tokens; only 2,000 remain.', 'Inspect sample quota result', 'This sample request cannot reserve its estimate now. Background work may wait for budget; an interactive request may report the limit. Repeated retries do not create headroom.'),
        step('reduce', 'Choose a smaller or paused task', 'Reduce scope, select an available lower-cost model where appropriate, or pause scheduled work. A model choice does not bypass host caps.', '/usage', 'Sample task: a broad recurring summary.', 'Preview a smaller task', 'Draft: a bounded summary of fewer sources, or pause the schedule until needed. No schedule, model preference or token limit changed.')
    ] },
    { id: 'admin.instance', roomId: 'host', version: 2, title: 'Host administration', hostOnly: true, requires: { operator: true }, steps: [
        step('invite', 'Preview an invitation', 'Only operators can open this tour. A live invitation grants access with the selected role; check the recipient and role first.', '/host', 'Sample invitation: member role, not issued.', 'Preview issuing an invitation', 'Fictional member invitation prepared. No link, token, account or permission was created.'),
        step('revoke', 'Revoke the right kind of access', 'Revoking an invitation stops that invitation link. An account already admitted needs its own account action.', '/host', 'Sample invitation: unused.', 'Preview revoking invitation', 'Sample link revoked. This would not disable an existing account. No real invitation changed.'),
        step('disable', 'Understand disabling an account', 'Disabling an account ends its sessions and keeps its data. It is not account erasure.', '/host', 'Fictional member account: active.', 'Preview disabling account', 'Sample account disabled; sessions ended, data retained. Your account and every other real account remain unchanged.'),
        step('capacity', 'Inspect aggregate capacity', 'Review host status and capacity before adding work. Token budgets and concurrent execution capacity are separate constraints.', '/host', 'Sample host: two execution slots occupied; token headroom available.', 'Inspect sample capacity', 'Work may wait for an execution slot even with tokens available. Aggregate health does not require reading private conversations.'),
        step('quota', 'Preview a token cap', 'Host Limits sets a token cap per account and its UTC window. Changes apply to new reservations; running replies finish. Non-token resources are tracked separately.', '/host', 'Sample cap: unset.', 'Preview setting a cap', 'Draft: 10,000 tokens per account per 24 hours. Held estimates plus settled usage count toward admission. No live quota or retention policy changed.'),
        step('failure', 'Review a failed integration safely', 'Inspect the reported failure and configuration status before retrying. Never paste credentials into feedback or logs.', '/host', 'Sample integration: delivery failed.', 'Inspect sample recovery', 'Check configuration and destination, then verify whether delivery already occurred. A live test send is an explicit action; this tour sends nothing.')
    ] }
];
