/** Safe, authored project/activity demonstrations. Actions change only the
 * browser preview; explicit Keep uses the existing separate sample-copy API. */
const step = (id, title, body, path, before, action, after, extra = {}) => ({
    id, title, body, path, demo: 'workflow', preview: { before, action, after }, ...extra
});
const project = (id, title, steps) => ({ id, title, roomId: 'projects', version: 2, requires: { feature: 'projects' }, steps });
const activity = (id, title, steps) => ({ id, title, roomId: 'activity', version: id === 'activity.inbox' ? 3 : 2, steps });
const P = '/projects';
const I = '/activity/inbox';
const S = '/activity/scheduled';

module.exports = [
    project('projects.basics', 'Projects basics', [
        step('goal', 'Give the work a goal', 'Projects hold ongoing work with a goal. This fictional project stays in the tour; nothing is created in your account.', P, 'Weekend field notebook: no goal yet.', 'Set sample goal', 'Goal: turn Saturday’s observations into a short, evidence-linked field report.'),
        step('scope', 'Inspect who can see it', 'New projects start private. A shared project and a private conversation have different audiences.', P, 'Weekend field notebook · Private.', 'Inspect sample audience', 'Only you can read this sample project. No invitation has been sent.'),
        step('note', 'Bring useful knowledge into the project', 'A private reference does not publish its source. Shared work needs an explicit published copy when other people must read it.', P, 'Tide-pool anemones: a private sample note.', 'Preview sample reference', 'The sample project references the note. Sharing a project later does not expose a private reference.'),
        step('conversation', 'Work in the project conversation', 'Project conversation provides project context. A chat outside the project remains a separate conversation.', P, 'Sample project → Conversation.', 'Preview sample question', 'Draft only: “Which observations support the field report?” No message or model request is sent.'),
        step('files-apps', 'Inspect files and apps', 'Check an artifact’s origin and version before reusing it. Opening the sample does not run code.', P, 'Sample artifacts: field-log.txt and Tide-pool counter v1.', 'Inspect sample origin', 'field-log.txt: supplied observation log. Tide-pool counter v1: generated in a sample Chat turn, not executed here.'),
        step('plan-output', 'Follow plan to result', 'Plans describe what should happen. Runs record attempts. Inspect the actual output before accepting a conclusion.', P, 'Plan: compare observations → draft report → verify citations.', 'Inspect sample run output', 'Sample completed run: report.md exists. Its limitation says that one walk is not a species survey.'),
        step('collaboration', 'Preview inviting and revoking', 'Inviting and revoking access are explicit project actions. Revocation cannot retract copies someone already downloaded.', P, 'Sample collaborator: not invited.', 'Preview invite and revoke', 'Simulation: collaborator invited, then access revoked. No real account, invitation or permission changed.')
    ]),
    project('projects.plans', 'Plans', [
        step('criteria', 'State what success means', 'A concrete success criterion makes a plan reviewable.', P, 'Goal: write a field report.', 'Add sample criteria', 'Success: a short report with one source for each observation and an explicit limits section.'),
        step('steps', 'Review the proposed steps', 'Check the order, dependencies and scope before allowing work.', P, 'Proposed plan: inspect log → draft → verify.', 'Inspect sample dependencies', 'Draft waits for the log; verification waits for the draft. Missing evidence remains a gap.'),
        step('approval', 'Separate approval from automatic work', 'Some steps need a human decision. Approval permits that step; it is not proof that the final result is correct.', P, 'Sample step: approval required. Automatic steps still obey host limits.', 'Approve sample step', 'Sample decision recorded locally in this preview. No real approval or execution occurred.'),
        step('evidence', 'Inspect evidence for a decision', 'A completed step should point to evidence you can inspect.', P, 'Sample conclusion: three kinds of anemone observed.', 'Open sample evidence', 'Fictional field log reports three kinds during one walk. It does not establish full coastal diversity.'),
        step('blocked', 'Handle a blocked or failed step', 'Read the reason before retrying. Supply missing input or revise the plan; do not invent a successful result.', P, 'Blocked: photo-roll counts were not supplied.', 'Preview revised step', 'Revised scope: report the observed kinds, omit numeric counts, and name the missing photo roll as a limitation.'),
        step('conclusion', 'Review the conclusion', 'Judge success against the original criteria. A plan finishing does not imply that you accepted or used its output.', P, 'Sample draft complete, not yet reviewed.', 'Compare with criteria', 'Sources and limitations are present; counts remain unavailable. Decide explicitly whether that narrower output is useful.')
    ]),
    project('projects.runs', 'Runs', [
        step('queued', 'Inspect a queued run', 'A run is one attempt at work. Queued means waiting, not complete. Live execution depends on host support and available capacity.', P, 'Sample run: QUEUED · waiting for capacity.', 'Inspect sample request', 'Requested output: report.md. Limits and inputs should be checked before a real run starts.'),
        step('start', 'Start the simulation', 'This button advances prepared sample state only. It never executes code or calls a provider.', P, 'Sample run: QUEUED.', 'Simulate start', 'Sample run: RUNNING · reading the fictional field log.'),
        step('logs', 'Read logs and outputs', 'Logs describe an attempt. Verify the promised files separately.', P, 'Sample log: writing report.', 'Inspect sample output', 'Sample output: report.md, with a source citation and a limitations section. A log saying “done” alone would not establish this.'),
        step('cancel', 'Cancel a second sample run', 'Cancellation stops further work where possible. An external action already taken may not be reversible.', P, 'Second sample run: RUNNING.', 'Simulate cancellation', 'Second sample run: cancelled. No actual run was started or cancelled.'),
        step('retry', 'Choose between resume and retry', 'Resume requires a valid checkpoint; retry starts another attempt and can incur cost. Check uncertain external outcomes before either.', P, 'Sample failed attempt: no usable checkpoint; external delivery outcome unknown.', 'Inspect recovery choices', 'Check whether delivery occurred before retrying. Do not blindly repeat an action that might already have succeeded.'),
        step('verify', 'Verify the required output', 'Accept a result only after inspecting the required output and its limitations. Execution disabled on the host does not prevent this safe tour.', P, 'Sample report.md: present, not yet accepted.', 'Verify sample contract', 'File, citation and limits are present. This preview records no real acceptance; review the actual artifact in a live run.')
    ]),
    activity('activity.inbox', 'Inbox', [
        step('result', 'Open a result and its source', 'Inbox is the delivery record for results, reminders and invitations. Follow the source to inspect the underlying work.', I, 'Sample Inbox item: field report ready.', 'Open sample result', 'Source: Weekend field notebook → sample run → report.md. No real item is opened or marked read.'),
        step('ask', 'Ask about an Inbox item', 'Ask Goobster opens private Chat with a removable context chip and an editable question. Nothing is sent until you send. Ask in the project uses its shared Conversation; members can see the reply.', I, 'Sample failed run: a required input is missing.', 'Preview Ask Goobster', 'Private Chat draft: “Why did this fail, and what should I do next?” Context chip: sample failed run. Remove the chip to ask without it. No real conversation, item or provider request is created.'),
        step('why', 'Understand why it appeared', 'A scheduled result, invitation and proactive notice have different causes. Look at the source before deciding what to do.', I, 'Sample notice: review the field report.', 'Inspect sample reason', 'Reason: a sample run completed. Proactive Attention is a separate opt-in feature, not enabled by this tour.'),
        step('notice-actions', 'Choose the appropriate notice action', 'Read and Archive affect Inbox. Act, Snooze and Dismiss apply to linked Attention notices when offered; archiving does not cancel the underlying work.', I, 'Sample linked notice: awaiting your attention.', 'Preview action choices', 'Act: record that you handled the notice. Snooze: revisit later. Dismiss: remove the notice. None of these sample choices changes an account item.'),
        step('approval', 'Review an approval request', 'Inspect who is asking, what would happen, and which project is involved. Approve only an action you intend.', I, 'Sample approval request: publish the private field report.', 'Preview declining approval', 'Sample decision: decline until audience and content are reviewed. No approval is sent and nothing is published.'),
        step('quiet-controls', 'Find quiet hours and proactive controls', 'Delivery preferences and Attention enrollment are separate controls. Change them deliberately in Settings; this preview changes neither.', '/settings', 'Sample delivery: Inbox, with quiet hours to inspect.', 'Inspect sample controls', 'Review quiet hours and delivery destination in Settings → Initiative. Attention enrollment remains unchanged. Use Ask Goobster on an Inbox item to bring its context into private Chat.')
    ]),
    activity('activity.scheduled', 'Scheduled', [
        step('reminder', 'Preview a one-time reminder', 'A reminder delivers your saved text at a time you choose. This sample creates no task.', S, 'Sample reminder: review the field report.', 'Preview reminder', 'Draft reminder: tomorrow at 09:00 in your selected timezone. Nothing scheduled.'),
        step('timezone', 'Check timezone and delivery', 'Confirm the timezone and destination before saving. A time shown in another timezone may be a different day.', S, 'Sample: 09:00 America/Denver → Inbox.', 'Inspect delivery preview', 'The preview must show the resolved next occurrence and destination. Check daylight-saving transitions; never assume a fixed UTC offset.'),
        step('recurring', 'Distinguish recurring AI work', 'Recurring AI tasks perform work and can use tokens on every run. Live execution needs a configured provider, host support and budget.', S, 'Sample recurring task: prepare a weekly field summary.', 'Preview recurring task', 'Draft only: weekly summary with a bounded scope. This differs from a reminder that delivers fixed text; no provider is called.'),
        step('next-run', 'Inspect the next run and pause', 'Check the displayed next occurrence. Pause and resume are explicit actions; missed work must not be assumed to have run.', S, 'Sample schedule: active; next run shown in your timezone.', 'Simulate pause and resume', 'Simulation: paused, then resumed. Verify the next displayed run before leaving. No real schedule changed.'),
        step('delivery-failure', 'Separate work from delivery failure', 'An output may exist even when delivery failed. Inspect the result before rerunning work that could cost tokens or duplicate an action.', S, 'Sample run: report created; notification delivery failed.', 'Inspect sample result', 'report.md is available at its source. Check the delivery destination and failure reason; do not regenerate solely because the notification failed.'),
        step('delete', 'Delete the sample task', 'Deleting a live schedule stops future scheduled work. It is not an account erasure or a guarantee that in-flight work can be recalled.', S, 'Sample recurring task: draft only.', 'Delete sample draft', 'Sample draft discarded in this preview. No account data, output, schedule or permission was changed.')
    ])
];
