/**
 * The manager's side of the native PostgreSQL cluster it owns
 * (documentation/native_postgres.md). Everything that needs root happens in
 * the privileged helper (`packages`, `postgres.cluster.*`, apps/manager/privileged);
 * everything the manager may look at without root (the distribution, the
 * packages, the clusters, the storage, the ports) is the read-only inventory in
 * `@goobster/core/db/native`. This file composes the two with the manager's
 * settings, the instance record (`<store>/native-postgres.json`) and the #338
 * connection library, which probes the application role like for any server.
 *
 * Secrets: the application password is generated by the caller and passed in.
 * Only its SCRAM-SHA-256 verifier reaches the helper (stdin of one process,
 * never an argv, a record, a plan, a journal, a result or a log line). The
 * application URL is staged in the overlay under a key that is never merged
 * into an environment (environment.js STAGED_KEYS) until `database.connect`
 * writes the live one.
 */

const nodeFs = require('node:fs');
const nodePath = require('node:path');
const { ManagerError } = require('../errors');
const environment = require('../environment');
const dbInit = require('../install/dbInit');
const { createInstallCore, exactKeys, parseBoolean } = require('../install/engine');
const { lazy } = require('../lazy');
const { createProbe } = require('../database/probe');
const input = require('../database/input');
const state = require('./state');
const owned = require('./owned');

const lib = lazy('@goobster/core/db/native');
const dockerContainers = lazy('@goobster/core/db/docker/containers');

const REQUEST_KEYS = new Set(['port', 'bind', 'acknowledgeLanBind', 'dataDirectory', 'role', 'database', 'installPackages', 'acknowledgeBackupTools', 'acknowledgeMount']);
const NAME = /^[a-z_][a-z0-9_]{0,62}$/;
const IPV4 = /^(?:\d{1,3}\.){3}\d{1,3}$/;
const REQUIRED_BYTES = 1024 * 1024 * 1024;
const STAGED = owned.STAGED;
const TIMEOUT = Object.freeze({ install: 30 * 60_000, create: 15 * 60_000, control: 5 * 60_000, remove: 10 * 60_000, relocate: 60 * 60_000 });
const FIRST_UNPRIVILEGED_PORT = 1024;

const finding = (code, severity, detail, remedy = '', extra = {}) => ({ code, severity, detail, remedy, ...extra });

function invalid(message) {
    return new ManagerError(400, 'INVALID_INPUT', message);
}

/** A core `NativeError` as the manager's error; anything else is returned unchanged. */
function mapNative(error) {
    if (!error || error.name !== 'NativeError') return error;
    const status = ['INVALID_INSTALLATION_ID', 'INVALID_CLUSTER_NAME'].includes(error.code) ? 400 : 409;
    return new ManagerError(status, error.code, error.message, error.details && Object.keys(error.details).length ? error.details : null);
}

async function mapped(call) {
    try {
        return await call();
    } catch (error) {
        throw mapNative(error);
    }
}

/**
 * The operator's request, validated. A bind address other than loopback is an
 * explicit choice (`acknowledgeLanBind`); the default never leaves this host.
 * The data directory is checked for shape here and against the machine in `assess`.
 */
function parseRequest(raw, { keys = REQUEST_KEYS, allowTransient = false } = {}) {
    const value = raw === undefined || raw === null ? {} : raw;
    exactKeys(value, keys, '"native"');
    const port = value.port === undefined ? 5432 : value.port;
    if (!Number.isInteger(port) || port < FIRST_UNPRIVILEGED_PORT || port > 65535) throw invalid(`"native.port" must be a whole number from ${FIRST_UNPRIVILEGED_PORT} to 65535.`);
    const bind = value.bind === undefined ? '127.0.0.1' : value.bind;
    if (typeof bind !== 'string' || !IPV4.test(bind) || bind.split('.').some(part => Number(part) > 255)) throw invalid('"native.bind" must be an IPv4 address (default 127.0.0.1).');
    const lan = bind !== '127.0.0.1';
    const acknowledgeLanBind = parseBoolean(value.acknowledgeLanBind, 'native.acknowledgeLanBind', false);
    if (lan && !acknowledgeLanBind) {
        throw new ManagerError(400, 'LAN_BIND_NOT_ACKNOWLEDGED', `Binding the database to ${bind === '0.0.0.0' ? 'every network interface' : bind} makes it reachable from other machines. Leave "native.bind" at 127.0.0.1, or set "native.acknowledgeLanBind" to accept that.`);
    }
    const role = value.role === undefined ? 'goobster' : value.role;
    const database = value.database === undefined ? 'goobster' : value.database;
    if (typeof role !== 'string' || !NAME.test(role) || role === 'postgres' || role === 'public' || role.startsWith('pg_')) throw invalid('"native.role" must be a lowercase role name (letters, digits, "_") other than "postgres".');
    if (typeof database !== 'string' || !NAME.test(database) || database === 'postgres' || database.startsWith('template')) throw invalid('"native.database" must be a lowercase database name other than "postgres" or a template.');
    let dataDirectory = null;
    if (value.dataDirectory !== undefined && value.dataDirectory !== null) {
        const checked = lib.paths.checkDataDirectory(value.dataDirectory, { allowTransient });
        if (!checked.ok) throw new ManagerError(400, checked.code, `"native.dataDirectory": ${checked.detail}`);
        dataDirectory = checked.path;
    }
    return {
        port,
        bind,
        lan,
        acknowledgeLanBind,
        dataDirectory,
        role,
        database,
        installPackages: parseBoolean(value.installPackages, 'native.installPackages', false),
        acknowledgeBackupTools: parseBoolean(value.acknowledgeBackupTools, 'native.acknowledgeBackupTools', false),
        acknowledgeMount: parseBoolean(value.acknowledgeMount, 'native.acknowledgeMount', false)
    };
}

/** The request as a plan or a response may show it: no secret exists in it. */
function publicRequest(request) {
    return {
        port: request.port,
        bind: request.bind,
        dataDirectory: request.dataDirectory,
        role: request.role,
        database: request.database,
        installPackages: request.installPackages,
        lan: request.lan
    };
}

function createNativeService({ settings, fs = nodeFs, now = () => new Date(), logger = console }) {
    const deps = () => settings.nativeDeps || {};
    const databaseDeps = () => settings.databaseDeps || {};
    const core = createInstallCore({ settings, fs, now, logger });
    const record = () => state.read(settings.storeDir, fs);

    function processEnv() {
        const base = { ...process.env };
        const own = settings.processEnv || {};
        for (const key of ['GOOBSTER_PG_BIN', 'PATH', 'FAKE_NATIVE_STATE']) {
            if (own[key] !== undefined) base[key] = own[key];
        }
        return base;
    }

    // ------------------------------------------------------------- elevation
    /** Whether a privileged helper can run at all here; never starts one. */
    function elevation() {
        const platform = deps().platform || process.platform;
        const implemented = core.privilegedAvailable('postgres.cluster.create');
        const injected = (core.deps.privilegedOptions || {}).elevation;
        let plan = injected || null;
        if (!plan && implemented && platform === 'linux') {
            try {
                plan = require('../privileged/linux').elevation({ env: settings.env || process.env, fs });
            } catch {
                plan = { kind: 'none', reason: 'UNKNOWN' };
            }
        }
        const kind = plan ? plan.kind : 'none';
        return { implemented, kind, available: implemented && kind !== 'none', reason: kind === 'none' ? (plan && plan.reason) || (implemented ? 'NO_ELEVATION' : 'NO_HELPER') : null };
    }

    /** The helper's answer as a result or a ManagerError. `scope` carries the operation record and context for the audit row. */
    async function privileged(operation, payload, { scope = {}, timeoutMs, manual = false } = {}) {
        const result = await core.runPrivileged(operation, payload, { record: scope.record || null, ctx: scope.ctx || null, timeoutMs, ...(manual ? { requestDir: nodePath.join(settings.storeDir, 'requests') } : {}) });
        if (result.status === 'deferred') {
            throw new ManagerError(501, 'NOT_IMPLEMENTED', 'There is no privileged helper for this operating system in this version.');
        }
        if (result.status === 'fallback') {
            throw new ManagerError(409, 'ELEVATION_UNAVAILABLE', 'The installer cannot get administrator rights here (it runs "sudo -n", or pkexec when a display is present). Run the manager as root, or allow it passwordless sudo for the helper, then try again.', { reason: result.reason || null, ...(result.manual ? { manual: result.manual } : {}) });
        }
        if (result.status === 'failed') {
            throw new ManagerError(409, result.code || 'HELPER_FAILED', result.message || 'The privileged helper failed.', { privileged: operation, log: result.log || [] });
        }
        return { outcome: result.outcome, detail: result.detail || {}, log: result.log || [], via: result.via || null };
    }

    // ------------------------------------------------------------ inspecting
    async function inspect({ doc = null, candidatePath = null, requiredBytes = REQUIRED_BYTES } = {}) {
        const given = deps();
        const runner = given.runner || lib.runner.createRunner({ env: processEnv() });
        return mapped(() => lib.inventory.inspectHost({
            fs,
            runner,
            env: processEnv(),
            record: doc ? { cluster: { name: doc.cluster.name, dataDirectory: doc.cluster.dataDirectory } } : null,
            candidatePath,
            requiredBytes,
            ...(given.distro ? { distro: given.distro } : {}),
            ...(given.platform ? { platform: given.platform } : {}),
            ...(given.arch ? { arch: given.arch } : {}),
            ...(typeof given.passwd === 'string' ? { passwd: given.passwd } : {}),
            ...(given.probePort ? { probePort: given.probePort } : {})
        }));
    }

    const resourceNames = (installationId, family, clusterName, dataDirectory) => {
        const name = clusterName || (installationId ? `goobster-${lib.names.shortId(installationId)}` : 'goobster');
        if (!family) return { cluster: name, service: null, dataDirectory: dataDirectory || null, template: !clusterName };
        const resources = lib.names.resourcesFor({ family, installationId, clusterName: name, dataDirectory });
        return { cluster: name, service: resources.service, configDirectory: resources.configDirectory, dataDirectory: resources.dataDirectory, template: !clusterName };
    };

    /** The host report as a response may show it: names, versions, ports and states; no foreign data directory. */
    function publicHost(report) {
        return {
            supported: report.supported,
            reason: report.reason,
            remedy: report.remedy,
            distro: report.distro ? { id: report.distro.id, version: report.distro.versionId || null, family: report.distro.family, arch: report.distro.arch || null, raspberryPi: Boolean(report.distro.raspberryPi), label: report.distro.label || null, tested: Boolean(report.distro.tested) } : null,
            packageManager: report.packageManager,
            major: report.major,
            packages: report.packages ? Object.fromEntries(Object.entries(report.packages).map(([role, item]) => [role, { names: item.names, installed: item.installed, version: item.version, availability: item.availability }])) : null,
            clusters: report.clusters.map(cluster => ({ version: cluster.version, name: cluster.name, port: cluster.port, online: cluster.online, owned: cluster.owned === true, ...(cluster.owned ? { dataDirectory: cluster.dataDirectory } : {}) })),
            systemd: report.systemd,
            selinux: report.selinux,
            backupTools: report.backupTools,
            storage: report.storage ? { path: report.storage.path, exists: report.storage.exists, isDirectory: report.storage.isDirectory, empty: report.storage.empty, freeBytes: report.storage.freeBytes, requiredBytes: report.storage.requiredBytes, mountIssues: report.storage.mountIssues, reachableByPostgres: report.storage.reachableByPostgres, blockedAt: report.storage.blockedAt, candidate: report.storage.candidate } : null,
            layout: report.layout ? { socketDir: report.layout.socketDir, binDir: report.layout.binDir, defaultDataParent: report.layout.defaultDataParent } : null
        };
    }

    function publicRecord(doc) {
        if (!doc) return null;
        return {
            step: doc.step,
            complete: doc.step === 'verified',
            family: doc.family,
            cluster: { name: doc.cluster.name, service: doc.cluster.service, dataDirectory: doc.cluster.dataDirectory, port: doc.cluster.port, bind: doc.cluster.bind, role: doc.cluster.role, database: doc.cluster.database },
            relocation: doc.relocation ? { from: doc.relocation.from, to: doc.relocation.to, step: doc.relocation.step } : null,
            updatedAt: doc.updatedAt
        };
    }

    /** True when the connection in effect is the cluster this manager owns (loopback, the recorded port). */
    function connectedToOwned(doc) {
        if (!doc || doc.step !== 'verified' || !settings.dbUrl) return false;
        try {
            const target = input.connectionLib.describeUrl(settings.dbUrl);
            return input.connectionLib.isLoopback(target.host) && Number(target.port) === doc.cluster.port;
        } catch {
            return false;
        }
    }

    /** The read-only view for `GET /native/status` and `database native status`. */
    async function status({ installationId = null, storagePath = null } = {}) {
        const read = record();
        const report = await inspect({ doc: read.doc, candidatePath: storagePath });
        const family = report.distro ? report.distro.family : null;
        const choice = chooseClusterName(report, installationId, read.doc);
        const view = {
            host: publicHost(report),
            elevation: elevation(),
            names: resourceNames(installationId, family, choice.template ? null : choice.name, read.doc ? read.doc.cluster.dataDirectory : null),
            record: publicRecord(read.doc),
            recordProblem: read.problem,
            owned: null,
            connected: connectedToOwned(read.doc)
        };
        if (read.doc) {
            const ours = report.clusters.find(cluster => cluster.owned);
            view.owned = ours ? { exists: true, online: ours.online, port: ours.port, version: ours.version } : { exists: false, online: false, port: null, version: null };
        }
        return view;
    }

    // ----------------------------------------------------------------- planning
    function chooseClusterName(report, installationId, doc) {
        if (doc) return { name: doc.cluster.name, reason: 'recorded' };
        const taken = report.clusters.filter(cluster => cluster.version === lib.MAJOR).map(cluster => cluster.name);
        if (!taken.includes('goobster')) return { name: 'goobster', reason: 'default' };
        if (!installationId) return { name: 'goobster-<id8>', reason: 'name-taken', template: true };
        return { name: lib.names.clusterNameFor(installationId, taken), reason: 'name-taken' };
    }

    /**
     * Everything provisioning needs to know before it changes anything: the
     * distribution, the packages, the clusters that exist (all of them left
     * alone), the port, the storage and the elevation. `blocks` stop the
     * operation; each carries a remedy. `installationId` is null while planning
     * a fresh install (the id exists only after the ownership step).
     */
    async function assess({ installationId, request }) {
        const read = record();
        const earlier = read.doc;
        const wanted = request.dataDirectory || (earlier ? earlier.cluster.dataDirectory : null);
        const report = await inspect({ doc: earlier && installationId && String(earlier.installationId).toLowerCase() === String(installationId).toLowerCase() ? earlier : null, candidatePath: wanted });
        const family = report.distro ? report.distro.family : null;
        const findings = [];
        const view = {
            host: publicHost(report),
            request: publicRequest(request),
            mode: 'fresh',
            names: null,
            cluster: null,
            port: { requested: request.port, chosen: request.port, free: null, reason: null, suggestion: null },
            storage: { path: null, defaulted: false },
            packages: { install: [], repository: null, willInstall: false, approved: request.installPackages },
            backupTools: report.backupTools,
            elevation: elevation(),
            findings,
            ok: false
        };

        if (!report.supported) {
            findings.push(finding(report.reason || 'HOST_UNSUPPORTED', 'block', report.remedy || 'A native PostgreSQL cluster cannot be installed on this host.', 'Connect to an existing PostgreSQL server (database connect), or use the Docker option.'));
            view.names = resourceNames(installationId, null, null, null);
            return finish(view);
        }

        const sameInstallation = earlier && installationId && String(earlier.installationId).toLowerCase() === String(installationId).toLowerCase();
        const choice = chooseClusterName(report, installationId, sameInstallation ? earlier : null);
        view.cluster = choice;
        const dataDirectory = request.dataDirectory || (sameInstallation ? earlier.cluster.dataDirectory : lib.paths.defaultDataDirectory(family, choice.name));
        view.storage = { path: dataDirectory, defaulted: !request.dataDirectory };
        view.names = resourceNames(installationId, family, choice.template ? null : choice.name, dataDirectory);
        if (choice.reason === 'name-taken') findings.push(finding('CLUSTER_NAME_CHOSEN', 'note', `A PostgreSQL cluster named "goobster" already exists on this machine and is not left changed, so this installation's cluster is named "${choice.name}".`, ''));

        // the record
        if (earlier && installationId && !sameInstallation) {
            findings.push(finding('RECORD_OF_ANOTHER_INSTALLATION', 'block', 'The manager store records a native database that belongs to another installation (it was kept when that installation was uninstalled).', 'Its cluster and data directory are still there. Remove them by uninstalling with removeNativeData next time, or by hand (pg_dropcluster / the unit file named in native-postgres.json), then try again.'));
        } else if (read.present && !earlier) {
            findings.push(finding('RECORD_UNREADABLE', 'block', 'native-postgres.json in the manager store cannot be read.', 'It was left as it is; inspect it, or move it away if the cluster is gone.'));
        } else if (sameInstallation) {
            if (earlier.step === 'verified') {
                findings.push(finding('ALREADY_PROVISIONED', 'block', 'This installation already has a native database.', 'Use "database native start", "stop", "repair" or "relocate". To start over, remove it first (uninstall with removeNativeData).'));
            } else {
                view.mode = 'resume';
                findings.push(finding('RESUME', 'note', `An earlier setup reached "${earlier.step}"; it continues from there with this installation's own cluster.`, ''));
            }
        }

        // the host
        if (!report.systemd.available) {
            findings.push(finding(family === 'rhel' ? 'SYSTEMD_UNAVAILABLE' : 'SYSTEMD_UNAVAILABLE_NOTE', family === 'rhel' ? 'block' : 'note', family === 'rhel' ? 'systemd is not running here, and on this distribution the cluster is a systemd service.' : 'systemd is not running here, so the cluster is not started at boot.', family === 'rhel' ? 'Use the Docker option, or connect to an existing server.' : 'It is started and stopped by the installer; start it yourself after a reboot.'));
        }
        if (!view.elevation.available) {
            findings.push(finding('ELEVATION_UNAVAILABLE', 'block', 'Installing and creating a database needs administrator rights, and none can be obtained here without a password prompt (the installer runs "sudo -n", or pkexec when a display is present).', 'Run the manager as root, allow it passwordless sudo, or use an existing server / the Docker option.', { reason: view.elevation.reason }));
        }
        if (request.lan) findings.push(finding('LAN_BIND', 'warn', `The database will listen on ${request.bind}, which other machines may reach (the installer opens no firewall port).`, 'Put a firewall in front of it, or bind 127.0.0.1.'));
        const selinux = report.selinux && report.selinux.present && /enforcing|permissive/i.test(report.selinux.mode || '');
        if (selinux) findings.push(finding('SELINUX_LABELS', 'note', `SELinux is ${String(report.selinux.mode).toLowerCase()}: the installer labels the data directory and the port for PostgreSQL (semanage fcontext / port) and runs restorecon on it.`, ''));

        // other clusters
        const foreign = report.clusters.filter(cluster => !cluster.owned);
        if (foreign.length > 0) {
            findings.push(finding('FOREIGN_CLUSTERS', 'note', `${foreign.length === 1 ? 'Another PostgreSQL cluster runs' : `${foreign.length} other PostgreSQL clusters run`} on this machine (${foreign.map(item => `${item.name} on ${item.port === null ? 'an unknown port' : item.port}`).join(', ')}). ${foreign.length === 1 ? 'It is' : 'They are'} never changed: no setting, role, database or file of ${foreign.length === 1 ? 'it' : 'them'} is touched.`, ''));
        }

        // packages
        const roles = ['server', 'client', 'pgvector', 'contrib'];
        const missing = roles.filter(role => report.packages[role].names.length > 0 && !report.packages[role].installed);
        const names = lib.packages.installNames(family, { selinux: Boolean(selinux) });
        const installed = new Set();
        for (const role of roles) if (report.packages[role].installed) for (const name of report.packages[role].names) installed.add(name);
        const toInstall = names.filter(name => !installed.has(name));
        view.packages.install = toInstall;
        view.packages.willInstall = toInstall.length > 0 && request.installPackages;
        const viaPgdg = missing.some(role => report.packages[role].availability === 'via-pgdg');
        view.packages.repository = toInstall.length > 0 && viaPgdg ? 'pgdg' : null;
        if (toInstall.length > 0) {
            const from = view.packages.repository ? `the PostgreSQL project's own repository (${family === 'debian' ? 'apt.postgresql.org' : 'download.postgresql.org'}), added with its signing key pinned by fingerprint` : `this distribution's package sources (${lib.packages.table(family).manager})`;
            if (!request.installPackages) {
                findings.push(finding('PACKAGES_NOT_APPROVED', 'block', `PostgreSQL ${lib.MAJOR} is not fully installed: ${toInstall.join(', ')} would be installed from ${from}.`, 'Tick "install the packages" to approve it, or install them yourself first.', { packages: toInstall, repository: view.packages.repository, acknowledge: 'installPackages' }));
            } else {
                findings.push(finding('PACKAGES_WILL_INSTALL', 'note', `${toInstall.join(', ')} will be installed from ${from}. They stay installed if this database is later removed.`, '', { packages: toInstall, repository: view.packages.repository }));
            }
        }
        const clientComing = !report.packages.client.installed && request.installPackages;
        const backup = report.backupTools;
        if (clientComing) {
            findings.push(finding('BACKUP_TOOLS_WILL_BE_INSTALLED', 'note', `The PostgreSQL ${lib.MAJOR} client tools, which Goobster's backups use, are part of the packages above.`, ''));
        } else if (backup && !backup.ok) {
            findings.push(finding(backup.code, request.acknowledgeBackupTools ? 'warn' : 'block', backup.code === 'BACKUP_TOOLS_MISSING' ? 'pg_dump is not installed here, so Goobster\'s backups cannot read this database.' : `The host's pg_dump (${backup.version || 'unknown'}) is older than the server's PostgreSQL ${lib.MAJOR}; it refuses to back it up.`, backup.remedy, { blocksBackups: true, acknowledge: 'acknowledgeBackupTools' }));
        }

        // port
        const own = sameInstallation ? report.clusters.find(cluster => cluster.owned) : null;
        if (own && own.port === request.port) {
            view.port.free = true;
        } else {
            const probe = deps().probePort || dockerContainers.probeListen;
            const taken = new Set(report.ports.inUse);
            const bind = request.bind === '0.0.0.0' ? '127.0.0.1' : request.bind;
            const free = async (port) => !taken.has(port) && await probe(port, bind);
            if (!(await free(request.port))) {
                view.port.free = false;
                view.port.reason = taken.has(request.port) ? 'CLUSTER_USES_PORT' : 'SOCKET_IN_USE';
                let next = null;
                for (let candidate = request.port + 1; candidate < Math.min(65536, request.port + 100); candidate++) {
                    if (await free(candidate)) { next = candidate; break; }
                }
                view.port.suggestion = next;
                findings.push(finding('PORT_IN_USE', 'block', taken.has(request.port) ? `Another PostgreSQL cluster on this machine already uses port ${request.port}.` : `Something on this machine already listens on port ${request.port}.`, next ? `Choose another port; ${next} is free.` : 'Choose another port.', { port: request.port, suggestion: next }));
            } else {
                view.port.free = true;
            }
        }

        // storage
        const resuming = sameInstallation && earlier.cluster.dataDirectory === dataDirectory;
        const checked = lib.paths.checkDataDirectory(dataDirectory, { allowTransient: deps().allowTransient === true });
        const storage = report.storage;
        if (!checked.ok) {
            findings.push(finding(checked.code, 'block', checked.detail, 'Choose another directory.'));
        } else if (lib.paths.isDistributionDirectory(family, dataDirectory)) {
            findings.push(finding('DATA_DIRECTORY_IS_DISTRIBUTION', 'block', 'That is the data directory of the distribution\'s own cluster.', 'Choose another directory; the installer never builds on top of an existing cluster.'));
        } else {
            const overlaps = report.clusters.filter(cluster => !cluster.owned && cluster.dataDirectory && (lib.paths.inside(cluster.dataDirectory, dataDirectory) || lib.paths.inside(dataDirectory, cluster.dataDirectory)));
            if (overlaps.length > 0) findings.push(finding('DATA_DIRECTORY_OVERLAPS', 'block', 'The chosen directory overlaps the data directory of another PostgreSQL cluster.', 'Choose a directory of its own.'));
            if (storage) {
                if (storage.exists && !storage.isDirectory) findings.push(finding('STORAGE_NOT_DIRECTORY', 'block', 'The chosen data directory exists and is not a directory.', 'Choose a directory, or a path that does not exist yet.'));
                else if (storage.isDirectory && storage.empty === false && !resuming) findings.push(finding('STORAGE_NOT_EMPTY', 'block', 'The chosen data directory is not empty. The installer builds a new database and never adopts or overwrites existing files.', 'Choose an empty or new directory, or move that one away yourself.'));
                if (storage.freeBytes !== null && storage.freeBytes < storage.requiredBytes) findings.push(finding('STORAGE_FULL', 'block', 'There is not enough free space for the database (1 GiB is the least).', 'Free some space, or choose another directory.', { freeBytes: storage.freeBytes, requiredBytes: storage.requiredBytes }));
                for (const issue of storage.mountIssues || []) {
                    if (issue.severity === 'note') {
                        findings.push(finding(issue.code, 'note', issue.code === 'FILESYSTEM_OVERLAY' ? 'The directory is on an overlay file system (typical in containers); its data lives only as long as the container does.' : 'The mount under the directory could not be identified.', ''));
                    } else if (issue.code === 'MOUNT_NOT_IN_FSTAB') {
                        findings.push(finding(request.acknowledgeMount ? 'MOUNT_NOT_IN_FSTAB_ACKNOWLEDGED' : 'MOUNT_NOT_IN_FSTAB', request.acknowledgeMount ? 'warn' : 'block', `The directory is on a mount (${storage.nearest || 'unknown'}) that is not listed in /etc/fstab, so it may be missing after a reboot.`, 'Add it to /etc/fstab, or accept the risk.', { acknowledge: 'acknowledgeMount' }));
                    } else {
                        const text = { MOUNT_NOT_PERSISTENT: 'The directory is on a file system that does not survive a reboot.', FILESYSTEM_UNSUPPORTED: 'A database cannot live on that kind of file system (no Unix ownership, modes or reliable locking).', MOUNT_READ_ONLY: 'The directory is on a read-only mount.' }[issue.code] || 'The directory is on an unsuitable mount.';
                        findings.push(finding(issue.code, 'block', text, 'Choose a directory on a local, writable disk.'));
                    }
                }
                if (storage.reachableByPostgres === false) findings.push(finding('STORAGE_UNREACHABLE', 'block', `The postgres account cannot enter ${storage.blockedAt || 'a parent of the chosen directory'}.`, 'Give it search permission on that directory, or choose another path (for example one under /var/lib/postgresql or /srv).', { blockedAt: storage.blockedAt }));
            }
        }
        return finish(view);
    }

    function finish(view) {
        view.ok = !view.findings.some(item => item.severity === 'block');
        view.blocks = view.findings.filter(item => item.severity === 'block').map(item => ({ code: item.code, detail: item.detail, remedy: item.remedy }));
        return view;
    }

    function assertAssessed(view) {
        if (view.ok) return;
        const codes = [...new Set(view.blocks.map(item => item.code))];
        throw new ManagerError(409, 'PREFLIGHT_FAILED', `The native database cannot be created yet: ${codes.join(', ')}.`, { findings: view.blocks.slice(0, 12) });
    }

    // ------------------------------------------------------ the instance record
    function startRecord({ installationId, request, view, operationId }) {
        const family = view.host.distro.family;
        const resources = lib.names.resourcesFor({ family, installationId, clusterName: view.names.cluster, dataDirectory: view.names.dataDirectory });
        return state.write(settings.storeDir, {
            installationId,
            family,
            distro: { id: view.host.distro.id || '', version: view.host.distro.version || '' },
            major: lib.MAJOR,
            cluster: { name: view.names.cluster, service: resources.service, dataDirectory: resources.dataDirectory, configDirectory: resources.configDirectory || null, port: request.port, bind: request.bind, role: request.role, database: request.database },
            step: 'planned',
            created: { cluster: false, packages: [] },
            operationId
        }, { fs, now });
    }

    const advance = (step, patch = {}) => state.update(settings.storeDir, { step, ...patch }, { fs, now });

    /** The record for this run: kept when an earlier run of the same installation left one, else started. */
    function recordFor({ installationId, request, view, operationId }) {
        const read = record();
        if (read.doc && String(read.doc.installationId).toLowerCase() === String(installationId).toLowerCase()) {
            return state.update(settings.storeDir, { operationId, cluster: { port: request.port, bind: request.bind, role: request.role, database: request.database } }, { fs, now });
        }
        return startRecord({ installationId, request, view, operationId });
    }

    // ---------------------------------------------------------- the packages
    async function installPackages({ installationId, request, view, operationId, scope }) {
        recordFor({ installationId, request, view, operationId });
        const names = view.packages.install;
        if (names.length === 0) {
            advance('packages');
            return { installed: [], skipped: true };
        }
        if (!request.installPackages) throw new ManagerError(409, 'PACKAGES_NOT_APPROVED', 'The PostgreSQL packages are not installed and installing them was not approved.');
        const out = await privileged('package.install', { names, ...(view.packages.repository ? { repository: view.packages.repository } : {}) }, { scope, timeoutMs: TIMEOUT.install, manual: true });
        advance('packages', { created: { packages: names } });
        return { installed: names, outcome: out.outcome };
    }

    // ----------------------------------------------------------- the cluster
    /** Create (or resume) the cluster, its role, database and extensions; only the verifier is sent. */
    async function createCluster({ installationId, request, view, password, scope }) {
        const doc = record().doc;
        if (!doc) throw new ManagerError(409, 'NO_NATIVE_DATABASE', 'The native database record is missing; plan again.');
        if (typeof password !== 'string' || password.length === 0) throw new ManagerError(409, 'PLAN_INPUT_LOST', 'The generated password was lost with the plan; plan again.');
        const out = await privileged('postgres.cluster.create', {
            installationId,
            managerStore: settings.storeDir,
            clusterName: doc.cluster.name,
            dataDirectory: doc.cluster.dataDirectory,
            port: doc.cluster.port,
            bind: doc.cluster.bind,
            lan: doc.cluster.bind !== '127.0.0.1',
            role: doc.cluster.role,
            database: doc.cluster.database,
            passwordVerifier: lib.scram.verifier(password),
            mode: 'create',
            ...(request.acknowledgeMount ? { acknowledgeMount: true } : {})
        }, { scope, timeoutMs: TIMEOUT.create });
        advance('provisioned', { created: { cluster: out.detail.created === true || doc.created.cluster } });
        return { created: out.detail.created === true, resumed: out.detail.resumed === true, provisioned: out.detail.provisioned === true };
    }

    /** The application's connection to the cluster: loopback, the chosen port, no TLS, the generated password. */
    function applicationConnection(doc, password) {
        return input.parseConnection({
            host: '127.0.0.1',
            port: doc.cluster.port,
            database: doc.cluster.database,
            schema: 'public',
            user: doc.cluster.role,
            password,
            tls: { mode: 'disable' }
        });
    }

    const urlOf = (application) => input.connectionLib.connectionUrl(application, { tlsMode: 'disable' });

    function stageUrl(url) {
        const existing = environment.read(settings.storeDir, fs).values;
        environment.write(settings.storeDir, { ...existing, [STAGED]: url }, { fs, now });
    }

    function removeStaged() {
        const existing = environment.read(settings.storeDir, fs);
        if (!existing.values[STAGED]) return false;
        const { [STAGED]: _gone, ...rest } = existing.values;
        if (Object.keys(rest).length === 0) environment.remove(settings.storeDir, fs);
        else environment.write(settings.storeDir, rest, { fs, now });
        return true;
    }

    async function applySchema({ roots, password }) {
        const doc = record().doc;
        const application = applicationConnection(doc, password);
        stageUrl(urlOf(application));
        const initialise = databaseDeps().initDatabase || dbInit.initDatabase;
        const out = await initialise({ roots: roots || { data: settings.dataDir, code: settings.root }, settings, database: { engine: 'postgres', external: true }, url: urlOf(application) });
        advance('schema');
        return { application, tables: out.tables };
    }

    async function verify({ application }) {
        const report = await createProbe(settings)(application);
        const found = report.schema ? report.schema.state : 'missing-schema';
        if (!report.reachable || found !== 'goobster-current') {
            throw new ManagerError(409, 'SCHEMA_NOT_CURRENT', `The new database's schema is ${found}; nothing else was changed.`);
        }
        advance('verified');
        return { schema: found, ok: report.verdict.ok };
    }

    // ------------------------------------------------------------- lifecycle
    function recorded() {
        const read = record();
        if (!read.doc) throw new ManagerError(409, 'NO_NATIVE_DATABASE', 'This manager has no native database record. Provision one first (database native provision).');
        return read.doc;
    }

    const identity = (doc, installationId) => ({ installationId: installationId || doc.installationId, managerStore: settings.storeDir, clusterName: doc.cluster.name });

    async function control(action, { installationId, scope }) {
        const doc = recorded();
        const out = await privileged('postgres.cluster.control', { ...identity(doc, installationId), action }, { scope, timeoutMs: TIMEOUT.control, manual: true });
        return { action, changed: out.outcome !== 'noop', running: out.detail.running === true };
    }

    const start = (params) => control('start', params);
    const stop = (params) => control('stop', params);

    /** What a repair would do: nothing, converge the cluster's configuration and start it, or refuse. */
    async function repairPlan({ installationId }) {
        const doc = recorded();
        const report = await inspect({ doc });
        const findings = [];
        const reasons = [];
        const ours = report.clusters.find(cluster => cluster.owned) || null;
        if (!report.supported) findings.push(finding(report.reason || 'HOST_UNSUPPORTED', 'block', report.remedy || 'This host is not supported.', ''));
        const view = elevation();
        if (!view.available) findings.push(finding('ELEVATION_UNAVAILABLE', 'block', 'Repairing needs administrator rights, and none can be obtained here without a password prompt.', 'Run the manager as root or allow passwordless sudo.'));
        if (report.supported && doc.family !== report.distro.family) findings.push(finding('DISTRO_CHANGED', 'block', 'The distribution family is not the one this database was created on.', 'Restore from a backup on a matching host.'));
        let action = 'none';
        if (report.supported && report.packages && !report.packages.server.installed) {
            findings.push(finding('SERVER_PACKAGE_MISSING', 'block', `The PostgreSQL ${lib.MAJOR} server package is no longer installed.`, 'Install it again (provision with "install the packages" approved), or restore from a backup.'));
        }
        if (!ours) {
            if (doc.family === 'debian') findings.push(finding('CLUSTER_MISSING', 'block', 'The cluster\'s configuration is gone from this machine. The installer does not re-adopt a data directory it can no longer describe.', 'Restore from a backup (documentation/backup_and_restore.md), or remove this record by uninstalling with removeNativeData.'));
            else if (report.storage && fs.existsSync(nodePath.join(doc.cluster.dataDirectory, 'PG_VERSION'))) { action = 'converge'; reasons.push('MISSING_SERVICE'); }
            else findings.push(finding('DATA_MISSING', 'block', 'The data directory is gone, so a new cluster would start empty.', 'Restore from a backup, or remove this record by uninstalling with removeNativeData and provision again.'));
        } else {
            if (ours.port !== null && ours.port !== doc.cluster.port) reasons.push('PORT_DRIFT');
            if (!ours.online) reasons.push('STOPPED');
            if (reasons.length > 0) action = 'converge';
        }
        const major = lib.planMajorChange({ currentMajor: doc.major });
        if (!major.ok) findings.push(finding(major.code, 'block', major.message, 'Back the database up and upgrade it by hand (documentation/native_postgres.md).', { from: major.from, to: major.to }));
        return { action, reasons, cluster: ours ? { name: ours.name, port: ours.port, online: ours.online } : null, request: publicRecord(doc).cluster, findings, ok: !findings.some(item => item.severity === 'block'), blocks: findings.filter(item => item.severity === 'block').map(item => ({ code: item.code, detail: item.detail, remedy: item.remedy })), installationId };
    }

    async function repair({ installationId, scope }) {
        const doc = recorded();
        const plan = await repairPlan({ installationId });
        if (!plan.ok) throw new ManagerError(409, 'PREFLIGHT_FAILED', `The native database cannot be repaired yet: ${[...new Set(plan.blocks.map(item => item.code))].join(', ')}.`, { findings: plan.blocks });
        if (plan.action === 'none') return { action: 'none', converged: false };
        const out = await privileged('postgres.cluster.create', {
            ...identity(doc, installationId),
            dataDirectory: doc.cluster.dataDirectory,
            port: doc.cluster.port,
            bind: doc.cluster.bind,
            lan: doc.cluster.bind !== '127.0.0.1',
            role: doc.cluster.role,
            database: doc.cluster.database,
            mode: 'converge'
        }, { scope, timeoutMs: TIMEOUT.create });
        return { action: plan.action, converged: true, outcome: out.outcome };
    }

    /** Wait for the cluster to accept connections on its port (bounded). */
    async function waitReady({ timeoutMs = 60_000 } = {}) {
        const { createReadiness } = require('./readiness');
        const out = await createReadiness({ settings, fs, now, logger }).waitReady({ timeoutMs, pollMs: deps().pollMs || 1000, ignoreConnection: true });
        if (!out.ready) throw new ManagerError(409, 'DATABASE_NOT_READY', `The native database did not answer (${out.reason}).`);
        return out;
    }

    // ------------------------------------------------------------ relocation
    /** The relocation, reviewed: the target must pass the same rules as a new data directory. */
    async function relocationPlan({ target, acknowledgeMount }) {
        const doc = recorded();
        const report = await inspect({ doc, candidatePath: target });
        const findings = [];
        const family = doc.family;
        if (!report.supported) findings.push(finding(report.reason || 'HOST_UNSUPPORTED', 'block', report.remedy || 'This host is not supported.', ''));
        if (doc.step !== 'verified') findings.push(finding('NO_NATIVE_DATABASE', 'block', 'There is no completed native database to relocate.', 'Provision one first.'));
        if (!elevation().available) findings.push(finding('ELEVATION_UNAVAILABLE', 'block', 'Relocating needs administrator rights, and none can be obtained here without a password prompt.', 'Run the manager as root or allow passwordless sudo.'));
        const checked = lib.paths.checkDataDirectory(target, { allowTransient: deps().allowTransient === true });
        if (!checked.ok) findings.push(finding(checked.code, 'block', checked.detail, 'Choose another directory.'));
        else if (target === doc.cluster.dataDirectory) findings.push(finding('ALREADY_THERE', 'block', 'The database already lives in that directory.', ''));
        else if (lib.paths.isDistributionDirectory(family, target)) findings.push(finding('DATA_DIRECTORY_IS_DISTRIBUTION', 'block', 'That is the data directory of the distribution\'s own cluster.', 'Choose another directory.'));
        else if (lib.paths.inside(doc.cluster.dataDirectory, target) || lib.paths.inside(target, doc.cluster.dataDirectory)) findings.push(finding('DATA_DIRECTORY_OVERLAPS', 'block', 'The target and the current data directory contain one another.', 'Choose a separate directory.'));
        else {
            const overlaps = report.clusters.filter(cluster => !cluster.owned && cluster.dataDirectory && (lib.paths.inside(cluster.dataDirectory, target) || lib.paths.inside(target, cluster.dataDirectory)));
            if (overlaps.length > 0) findings.push(finding('DATA_DIRECTORY_OVERLAPS', 'block', 'The target overlaps the data directory of another PostgreSQL cluster.', 'Choose a directory of its own.'));
            const storage = report.storage;
            const resuming = doc.relocation && doc.relocation.to === target;
            if (storage) {
                if (storage.exists && !storage.isDirectory) findings.push(finding('STORAGE_NOT_DIRECTORY', 'block', 'The target exists and is not a directory.', ''));
                else if (storage.isDirectory && storage.empty === false && !resuming) findings.push(finding('STORAGE_NOT_EMPTY', 'block', 'The target directory is not empty.', 'Choose an empty or new directory.'));
                if (storage.freeBytes !== null && storage.freeBytes < storage.requiredBytes) findings.push(finding('STORAGE_FULL', 'block', 'There is not enough free space at the target (1 GiB is the least; the helper checks the size of the database too).', ''));
                for (const issue of storage.mountIssues || []) {
                    if (issue.severity === 'note') continue;
                    if (issue.code === 'MOUNT_NOT_IN_FSTAB') findings.push(finding(acknowledgeMount ? 'MOUNT_NOT_IN_FSTAB_ACKNOWLEDGED' : 'MOUNT_NOT_IN_FSTAB', acknowledgeMount ? 'warn' : 'block', 'The target is on a mount that is not listed in /etc/fstab.', 'Add it to /etc/fstab, or accept the risk.', { acknowledge: 'acknowledgeMount' }));
                    else findings.push(finding(issue.code, 'block', 'The target is on an unsuitable file system or mount.', 'Choose a local, writable, persistent disk.'));
                }
                if (storage.reachableByPostgres === false) findings.push(finding('STORAGE_UNREACHABLE', 'block', `The postgres account cannot enter ${storage.blockedAt || 'a parent of the target'}.`, 'Give it search permission, or choose another path.', { blockedAt: storage.blockedAt }));
            }
        }
        return { from: doc.cluster.dataDirectory, to: target, findings, ok: !findings.some(item => item.severity === 'block'), blocks: findings.filter(item => item.severity === 'block').map(item => ({ code: item.code, detail: item.detail, remedy: item.remedy })) };
    }

    /** Write the intent the helper checks, then ask for the move. The old directory is kept. */
    async function relocate({ installationId, target, acknowledgeMount, scope }) {
        const doc = recorded();
        state.update(settings.storeDir, { relocation: { from: doc.cluster.dataDirectory, to: target, step: 'copied', backupVerified: true } }, { fs, now });
        const out = await privileged('postgres.cluster.relocate', { ...identity(doc, installationId), target, ...(acknowledgeMount ? { acknowledgeMount: true } : {}) }, { scope, timeoutMs: TIMEOUT.relocate });
        const resources = lib.names.resourcesFor({ family: doc.family, installationId: doc.installationId, clusterName: doc.cluster.name, dataDirectory: target });
        state.update(settings.storeDir, { cluster: { dataDirectory: target, configDirectory: resources.configDirectory || null }, relocation: null }, { fs, now });
        return { moved: out.outcome !== 'noop', from: doc.cluster.dataDirectory, to: target, kept: doc.cluster.dataDirectory };
    }

    function noteBackup() {
        const read = record();
        if (read.doc && read.doc.relocation) state.update(settings.storeDir, { relocation: { ...read.doc.relocation, step: 'backup', backupVerified: true } }, { fs, now });
    }

    /** Record the intent before the backup so an interruption is visible. */
    function planRelocation({ target }) {
        const doc = recorded();
        return state.update(settings.storeDir, { relocation: { from: doc.cluster.dataDirectory, to: target, step: 'planned', backupVerified: false } }, { fs, now });
    }

    function clearRelocation() {
        const read = record();
        if (read.doc && read.doc.relocation) state.update(settings.storeDir, { relocation: null }, { fs, now });
    }

    // ------------------------------------------------------------- uninstall
    /** What an uninstall with `removeNativeData` would delete, by name. */
    async function removalPlan({ installationId }) {
        const read = record();
        if (!read.present) return { present: false, resources: [], record: null };
        const doc = read.doc;
        const names = doc ? resourceNames(installationId, doc.family, doc.cluster.name, doc.cluster.dataDirectory) : resourceNames(installationId, null, null, null);
        const resources = [];
        if (doc) {
            resources.push({ kind: 'cluster', name: doc.cluster.name });
            resources.push({ kind: 'service', name: doc.cluster.service });
            resources.push({ kind: 'data-directory', name: doc.cluster.dataDirectory });
        }
        return { present: true, record: publicRecord(doc), names, resources, keptPackages: true };
    }

    /** Stop (keep the data) or remove (explicit scope). Packages and the repository stay installed. */
    async function retire({ installationId, remove, scope }) {
        const read = record();
        if (!read.present) return { present: false };
        const doc = read.doc;
        const out = { present: true, stopped: false, removed: false, dataKept: true };
        if (!doc) return out;
        const result = await privileged('postgres.cluster.remove', { ...identity(doc, installationId), removeData: remove === true }, { scope, timeoutMs: TIMEOUT.remove });
        out.stopped = true;
        if (remove) {
            out.removed = result.detail.removed === true || result.outcome === 'noop';
            out.dataKept = result.detail.dataKept === true;
            removeStaged();
            state.remove(settings.storeDir, fs);
        }
        return out;
    }

    return {
        parseRequest, publicRequest, inspect, status, assess, assertAssessed, elevation, privileged, recordFor, installPackages, createCluster,
        applySchema, verify, applicationConnection, urlOf, stageUrl, removeStaged, start, stop, repairPlan, repair, waitReady,
        relocationPlan, relocate, planRelocation, noteBackup, clearRelocation, removalPlan, retire, record, connectedToOwned, resourceNames,
        publicRecord, publicHost, advance, logger, now
    };
}

module.exports = { createNativeService, parseRequest, publicRequest, STAGED, REQUEST_KEYS, REQUIRED_BYTES, TIMEOUT, mapNative, mapped };
