name: Build and Deploy to Azure Container Apps

on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: [ main ]
    paths:
    - '**'
    - '.github/workflows/main.yml'

  # Allow manual trigger 
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
  # Note: DISCORD_GUILD_IDS should be a JSON array in the GitHub secret
  # Example format in the secret: ["123456789", "987654321"]
  DISCORD_GUILD_IDS: ${{ secrets.DISCORD_GUILD_IDS }}
  DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  AZURE_SPEECH_KEY: ${{ secrets.AZURE_SPEECH_KEY }}
  AZURE_REGION: eastus
  AZURE_SQL_USER: ${{ secrets.AZURE_SQL_USER }}
  AZURE_SQL_PASSWORD: ${{ secrets.AZURE_SQL_PASSWORD }}
  AZURE_SQL_DATABASE: ${{ secrets.AZURE_SQL_DATABASE }}
  AZURE_SQL_SERVER: ${{ secrets.AZURE_SQL_SERVER }}
  REPLICATE_API_KEY: ${{ secrets.REPLICATE_API_KEY }}
  PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev  # Specify the environment where secrets are stored

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CAGOOBSTER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CAGOOBSTER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CAGOOBSTER_AZURE_SUBSCRIPTION_ID }}

      # Create config.json directly
      - name: Create config.json
        run: |
          echo '{
            "clientId": "${{ secrets.DISCORD_CLIENT_ID }}",
            "guildIds": ${{ secrets.DISCORD_GUILD_IDS }},
            "token": "${{ secrets.DISCORD_BOT_TOKEN }}",
            "openaiKey": "${{ secrets.OPENAI_API_KEY }}",
            "azure": {
              "speech": {
                "key": "${{ secrets.AZURE_SPEECH_KEY }}",
                "region": "eastus",
                "language": "en-US"
              },
              "sql": {
                "user": "${{ secrets.AZURE_SQL_USER }}",
                "password": "${{ secrets.AZURE_SQL_PASSWORD }}",
                "database": "${{ secrets.AZURE_SQL_DATABASE }}",
                "server": "${{ secrets.AZURE_SQL_SERVER }}",
                "options": {
                  "encrypt": true,
                  "trustServerCertificate": false
                }
              }
            },
            "replicate": {
              "apiKey": "${{ secrets.REPLICATE_API_KEY }}"
            },
            "perplexity": {
              "apiKey": "${{ secrets.PERPLEXITY_API_KEY }}"
            },
            "DEFAULT_PROMPT": "You are Goobster, a quirky and clever Discord bot with a passion for helping users and a dash of playful sass. You love making witty observations and dropping the occasional pun, but you always stay focused on being genuinely helpful.\n\nKey Traits:\n- Friendly and approachable, but not afraid to show personality\n- Loves making clever wordplay and references when appropriate\n- Takes pride in being accurate and helpful\n- Excited about learning new things alongside users\n\nYou have access to real-time web search capabilities through the /search command. When users ask for current information or facts you are not certain about, you should:\n\n1. Acknowledge their request with enthusiasm\n2. Use the /search command by replying with a message in this EXACT format (including quotes):\n   \"/search query:\"your search query here\" reason:\"why you need this information\"\"\n\nExample responses:\n\nWhen needing current info:\n\"Let me check the latest data on that! /search query:\"current cryptocurrency market trends March 2024\" reason:\"User asked about crypto prices, and even a bot as clever as me needs up-to-date numbers to give accurate advice!\"\"\n\nWhen verifying facts:\n\"I want to make sure I give you the most accurate info! /search query:\"latest Mars rover discoveries 2024\" reason:\"Need to verify recent Mars exploration data\"\"\n\nRemember:\n- Be enthusiastic but professional\n- Make search queries specific and focused\n- Use appropriate emojis and formatting to make responses engaging\n- Stay helpful and informative while maintaining your quirky personality"
          }' | jq '.' > config.json

      - name: Update container app configuration
        run: |
          sed -i "s/\${IMAGE_TAG}/${{ github.sha }}/g" containerapp.yaml

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          registryUrl: nervouslabsdev.azurecr.io
          registryUsername: ${{ secrets.CAGOOBSTER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CAGOOBSTER_REGISTRY_PASSWORD }}
          containerAppName: ca-goobster
          resourceGroup: rg-sharedresources-dev
          containerAppEnvironment: ca-env-goobster
          targetPort: 3000
          ingress: external
          imageToBuild: nervouslabsdev.azurecr.io/ca-goobster:${{ github.sha }}
          yamlConfigPath: containerapp.yaml 